// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storageserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_SUCCESS Response_Status = 0
	Response_ERROR   Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR",
}
var Response_Status_value = map[string]int32{
	"SUCCESS": 0,
	"ERROR":   1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{1, 0}
}

type PartitionInfo_PartitionState int32

const (
	PartitionInfo_UNKNOWN     PartitionInfo_PartitionState = 0
	PartitionInfo_ONLINE      PartitionInfo_PartitionState = 1
	PartitionInfo_OFFLINE     PartitionInfo_PartitionState = 2
	PartitionInfo_ERROR       PartitionInfo_PartitionState = 3
	PartitionInfo_REMOVED     PartitionInfo_PartitionState = 4
	PartitionInfo_MAINTENANCE PartitionInfo_PartitionState = 5
)

var PartitionInfo_PartitionState_name = map[int32]string{
	0: "UNKNOWN",
	1: "ONLINE",
	2: "OFFLINE",
	3: "ERROR",
	4: "REMOVED",
	5: "MAINTENANCE",
}
var PartitionInfo_PartitionState_value = map[string]int32{
	"UNKNOWN":     0,
	"ONLINE":      1,
	"OFFLINE":     2,
	"ERROR":       3,
	"REMOVED":     4,
	"MAINTENANCE": 5,
}

func (x PartitionInfo_PartitionState) String() string {
	return proto.EnumName(PartitionInfo_PartitionState_name, int32(x))
}
func (PartitionInfo_PartitionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{21, 0}
}

type PartitionInfo_BlockBinInfo_BlockBinState int32

const (
	PartitionInfo_BlockBinInfo_ONLINE PartitionInfo_BlockBinInfo_BlockBinState = 0
	PartitionInfo_BlockBinInfo_ERROR  PartitionInfo_BlockBinInfo_BlockBinState = 1
)

var PartitionInfo_BlockBinInfo_BlockBinState_name = map[int32]string{
	0: "ONLINE",
	1: "ERROR",
}
var PartitionInfo_BlockBinInfo_BlockBinState_value = map[string]int32{
	"ONLINE": 0,
	"ERROR":  1,
}

func (x PartitionInfo_BlockBinInfo_BlockBinState) String() string {
	return proto.EnumName(PartitionInfo_BlockBinInfo_BlockBinState_name, int32(x))
}
func (PartitionInfo_BlockBinInfo_BlockBinState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{21, 0, 0}
}

type Event_Severity int32

const (
	Event_INFORMATIONAL Event_Severity = 0
	Event_CLEAR         Event_Severity = 1
	Event_WARNING       Event_Severity = 2
	Event_MINOR         Event_Severity = 3
	Event_MAJOR         Event_Severity = 4
	Event_CRITICAL      Event_Severity = 5
)

var Event_Severity_name = map[int32]string{
	0: "INFORMATIONAL",
	1: "CLEAR",
	2: "WARNING",
	3: "MINOR",
	4: "MAJOR",
	5: "CRITICAL",
}
var Event_Severity_value = map[string]int32{
	"INFORMATIONAL": 0,
	"CLEAR":         1,
	"WARNING":       2,
	"MINOR":         3,
	"MAJOR":         4,
	"CRITICAL":      5,
}

func (x Event_Severity) String() string {
	return proto.EnumName(Event_Severity_name, int32(x))
}
func (Event_Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{29, 0}
}

type Request struct {
	Version         int64  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MessageCheckSum []byte `protobuf:"bytes,2,opt,name=messageCheckSum,proto3" json:"messageCheckSum,omitempty"`
	Context         []byte `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	RequestId       string `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Origin          string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Timeout         uint64 `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Types that are valid to be assigned to Ping:
	//	*Request_PingRequest
	Ping                 isRequest_Ping `protobuf_oneof:"Ping"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Request) GetMessageCheckSum() []byte {
	if m != nil {
		return m.MessageCheckSum
	}
	return nil
}

func (m *Request) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Request) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Request) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Request) GetTimeout() uint64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type isRequest_Ping interface {
	isRequest_Ping()
}

type Request_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,1000,opt,name=pingRequest,proto3,oneof"`
}

func (*Request_PingRequest) isRequest_Ping() {}

func (m *Request) GetPing() isRequest_Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *Request) GetPingRequest() *PingRequest {
	if x, ok := m.GetPing().(*Request_PingRequest); ok {
		return x.PingRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_PingRequest)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// Ping
	switch x := m.Ping.(type) {
	case *Request_PingRequest:
		b.EncodeVarint(1000<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Ping has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 1000: // Ping.pingRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PingRequest)
		err := b.DecodeMessage(msg)
		m.Ping = &Request_PingRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// Ping
	switch x := m.Ping.(type) {
	case *Request_PingRequest:
		s := proto.Size(x.PingRequest)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

//
// Base response message
// All responses are wrapped inside of this message
//
type Response struct {
	// used for dealing with changes in protocol messages
	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Used generically for success/failure of request. Additional information
	// may be provided by the errorMessage field and child response message may have additional
	// states/messages
	Status          Response_Status `protobuf:"varint,2,opt,name=status,proto3,enum=storageserver.Response_Status" json:"status,omitempty"`
	MessageCheckSum []byte          `protobuf:"bytes,3,opt,name=messageCheckSum,proto3" json:"messageCheckSum,omitempty"`
	// Used generically
	ErrorMessage string `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	// If included will be returned in the response
	Context              []byte   `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	RequestId            string   `protobuf:"bytes,6,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_SUCCESS
}

func (m *Response) GetMessageCheckSum() []byte {
	if m != nil {
		return m.MessageCheckSum
	}
	return nil
}

func (m *Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Response) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Response) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type RequestMetadata struct {
	ChunkSize            uint32   `protobuf:"varint,1,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	ChunkOffset          uint64   `protobuf:"varint,2,opt,name=chunkOffset,proto3" json:"chunkOffset,omitempty"`
	ShouldCache          bool     `protobuf:"varint,3,opt,name=shouldCache,proto3" json:"shouldCache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMetadata) Reset()         { *m = RequestMetadata{} }
func (m *RequestMetadata) String() string { return proto.CompactTextString(m) }
func (*RequestMetadata) ProtoMessage()    {}
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{2}
}
func (m *RequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMetadata.Unmarshal(m, b)
}
func (m *RequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMetadata.Marshal(b, m, deterministic)
}
func (dst *RequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMetadata.Merge(dst, src)
}
func (m *RequestMetadata) XXX_Size() int {
	return xxx_messageInfo_RequestMetadata.Size(m)
}
func (m *RequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMetadata proto.InternalMessageInfo

func (m *RequestMetadata) GetChunkSize() uint32 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func (m *RequestMetadata) GetChunkOffset() uint64 {
	if m != nil {
		return m.ChunkOffset
	}
	return 0
}

func (m *RequestMetadata) GetShouldCache() bool {
	if m != nil {
		return m.ShouldCache
	}
	return false
}

//
// Calls datasync on the specified file
// Used when WriteRequest sets syncOnWrite = false as a final step
// to ensure data was written fully to disk
type SyncBlockBinRequest struct {
	PartitionUuid        string           `protobuf:"bytes,1,opt,name=partitionUuid,proto3" json:"partitionUuid,omitempty"`
	FileName             string           `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Metadata             *RequestMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SyncBlockBinRequest) Reset()         { *m = SyncBlockBinRequest{} }
func (m *SyncBlockBinRequest) String() string { return proto.CompactTextString(m) }
func (*SyncBlockBinRequest) ProtoMessage()    {}
func (*SyncBlockBinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{3}
}
func (m *SyncBlockBinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncBlockBinRequest.Unmarshal(m, b)
}
func (m *SyncBlockBinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncBlockBinRequest.Marshal(b, m, deterministic)
}
func (dst *SyncBlockBinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncBlockBinRequest.Merge(dst, src)
}
func (m *SyncBlockBinRequest) XXX_Size() int {
	return xxx_messageInfo_SyncBlockBinRequest.Size(m)
}
func (m *SyncBlockBinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncBlockBinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncBlockBinRequest proto.InternalMessageInfo

func (m *SyncBlockBinRequest) GetPartitionUuid() string {
	if m != nil {
		return m.PartitionUuid
	}
	return ""
}

func (m *SyncBlockBinRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *SyncBlockBinRequest) GetMetadata() *RequestMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// used to help identify response of SyncBlockBinRequest
type SyncBlockBinResponse struct {
	ServerStartTime      string   `protobuf:"bytes,1,opt,name=serverStartTime,proto3" json:"serverStartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncBlockBinResponse) Reset()         { *m = SyncBlockBinResponse{} }
func (m *SyncBlockBinResponse) String() string { return proto.CompactTextString(m) }
func (*SyncBlockBinResponse) ProtoMessage()    {}
func (*SyncBlockBinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{4}
}
func (m *SyncBlockBinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncBlockBinResponse.Unmarshal(m, b)
}
func (m *SyncBlockBinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncBlockBinResponse.Marshal(b, m, deterministic)
}
func (dst *SyncBlockBinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncBlockBinResponse.Merge(dst, src)
}
func (m *SyncBlockBinResponse) XXX_Size() int {
	return xxx_messageInfo_SyncBlockBinResponse.Size(m)
}
func (m *SyncBlockBinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncBlockBinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncBlockBinResponse proto.InternalMessageInfo

func (m *SyncBlockBinResponse) GetServerStartTime() string {
	if m != nil {
		return m.ServerStartTime
	}
	return ""
}

//
// Writes a block of data to the specified location
type WriteRequest struct {
	PartitionUuid  string `protobuf:"bytes,1,opt,name=partitionUuid,proto3" json:"partitionUuid,omitempty"`
	FileName       string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	StartingOffset int64  `protobuf:"varint,3,opt,name=startingOffset,proto3" json:"startingOffset,omitempty"`
	DataLength     int64  `protobuf:"varint,4,opt,name=dataLength,proto3" json:"dataLength,omitempty"`
	SyncOnWrite    bool   `protobuf:"varint,5,opt,name=syncOnWrite,proto3" json:"syncOnWrite,omitempty"`
	// if present will compare against checksum calculated by server
	// if checksums do not match an error will be returned
	// calculated checksum in response will always be returned regardless
	DataCheckSum []byte `protobuf:"bytes,6,opt,name=dataCheckSum,proto3" json:"dataCheckSum,omitempty"`
	// if present and true, storage server will not write data to the disk
	// this flag is only used for testing storage server
	SkipWrite            bool             `protobuf:"varint,7,opt,name=skipWrite,proto3" json:"skipWrite,omitempty"`
	Metadata             *RequestMetadata `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{5}
}
func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (dst *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(dst, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetPartitionUuid() string {
	if m != nil {
		return m.PartitionUuid
	}
	return ""
}

func (m *WriteRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *WriteRequest) GetStartingOffset() int64 {
	if m != nil {
		return m.StartingOffset
	}
	return 0
}

func (m *WriteRequest) GetDataLength() int64 {
	if m != nil {
		return m.DataLength
	}
	return 0
}

func (m *WriteRequest) GetSyncOnWrite() bool {
	if m != nil {
		return m.SyncOnWrite
	}
	return false
}

func (m *WriteRequest) GetDataCheckSum() []byte {
	if m != nil {
		return m.DataCheckSum
	}
	return nil
}

func (m *WriteRequest) GetSkipWrite() bool {
	if m != nil {
		return m.SkipWrite
	}
	return false
}

func (m *WriteRequest) GetMetadata() *RequestMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type WriteResponse struct {
	// Hash of the data written so the client can
	// verify if the data was correct or not and take
	// the appropriate action.
	DataCheckSum []byte `protobuf:"bytes,1,opt,name=dataCheckSum,proto3" json:"dataCheckSum,omitempty"`
	// if syncOnWrite = false, returns start time of
	// server to know if a reset happened between the call
	// to write and the call to sync to disk
	ServerStartTime      string   `protobuf:"bytes,2,opt,name=serverStartTime,proto3" json:"serverStartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{6}
}
func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (dst *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(dst, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetDataCheckSum() []byte {
	if m != nil {
		return m.DataCheckSum
	}
	return nil
}

func (m *WriteResponse) GetServerStartTime() string {
	if m != nil {
		return m.ServerStartTime
	}
	return ""
}

//
// Read the requested block
type ReadRequest struct {
	PartitionUuid        string           `protobuf:"bytes,1,opt,name=partitionUuid,proto3" json:"partitionUuid,omitempty"`
	FileName             string           `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	StartingOffset       int64            `protobuf:"varint,3,opt,name=startingOffset,proto3" json:"startingOffset,omitempty"`
	DataLength           int64            `protobuf:"varint,4,opt,name=dataLength,proto3" json:"dataLength,omitempty"`
	Metadata             *RequestMetadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{7}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (dst *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(dst, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetPartitionUuid() string {
	if m != nil {
		return m.PartitionUuid
	}
	return ""
}

func (m *ReadRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ReadRequest) GetStartingOffset() int64 {
	if m != nil {
		return m.StartingOffset
	}
	return 0
}

func (m *ReadRequest) GetDataLength() int64 {
	if m != nil {
		return m.DataLength
	}
	return 0
}

func (m *ReadRequest) GetMetadata() *RequestMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ReadResponse struct {
	DataLength           int64    `protobuf:"varint,1,opt,name=dataLength,proto3" json:"dataLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{8}
}
func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (dst *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(dst, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetDataLength() int64 {
	if m != nil {
		return m.DataLength
	}
	return 0
}

// calculates a checksum based on the data provided and
// returns it in the response
type VerifyDataRequest struct {
	PartitionUuid        string   `protobuf:"bytes,1,opt,name=partitionUuid,proto3" json:"partitionUuid,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	StartingOffset       int64    `protobuf:"varint,3,opt,name=startingOffset,proto3" json:"startingOffset,omitempty"`
	DataLength           int64    `protobuf:"varint,4,opt,name=dataLength,proto3" json:"dataLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyDataRequest) Reset()         { *m = VerifyDataRequest{} }
func (m *VerifyDataRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyDataRequest) ProtoMessage()    {}
func (*VerifyDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{9}
}
func (m *VerifyDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyDataRequest.Unmarshal(m, b)
}
func (m *VerifyDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyDataRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyDataRequest.Merge(dst, src)
}
func (m *VerifyDataRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyDataRequest.Size(m)
}
func (m *VerifyDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyDataRequest proto.InternalMessageInfo

func (m *VerifyDataRequest) GetPartitionUuid() string {
	if m != nil {
		return m.PartitionUuid
	}
	return ""
}

func (m *VerifyDataRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *VerifyDataRequest) GetStartingOffset() int64 {
	if m != nil {
		return m.StartingOffset
	}
	return 0
}

func (m *VerifyDataRequest) GetDataLength() int64 {
	if m != nil {
		return m.DataLength
	}
	return 0
}

type VerifyDataResponse struct {
	DataCheckSum         []byte   `protobuf:"bytes,1,opt,name=dataCheckSum,proto3" json:"dataCheckSum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyDataResponse) Reset()         { *m = VerifyDataResponse{} }
func (m *VerifyDataResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyDataResponse) ProtoMessage()    {}
func (*VerifyDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{10}
}
func (m *VerifyDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyDataResponse.Unmarshal(m, b)
}
func (m *VerifyDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyDataResponse.Marshal(b, m, deterministic)
}
func (dst *VerifyDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyDataResponse.Merge(dst, src)
}
func (m *VerifyDataResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyDataResponse.Size(m)
}
func (m *VerifyDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyDataResponse proto.InternalMessageInfo

func (m *VerifyDataResponse) GetDataCheckSum() []byte {
	if m != nil {
		return m.DataCheckSum
	}
	return nil
}

// pull request from another storage server
type CopyFromRequest struct {
	// server to connect to - host:port
	SourceServerName     string   `protobuf:"bytes,1,opt,name=sourceServerName,proto3" json:"sourceServerName,omitempty"`
	SoucePartitionUuid   string   `protobuf:"bytes,2,opt,name=soucePartitionUuid,proto3" json:"soucePartitionUuid,omitempty"`
	SourceFileName       string   `protobuf:"bytes,3,opt,name=sourceFileName,proto3" json:"sourceFileName,omitempty"`
	SourceStartingOffset string   `protobuf:"bytes,4,opt,name=sourceStartingOffset,proto3" json:"sourceStartingOffset,omitempty"`
	PartitionUuid        string   `protobuf:"bytes,5,opt,name=partitionUuid,proto3" json:"partitionUuid,omitempty"`
	FileName             string   `protobuf:"bytes,6,opt,name=fileName,proto3" json:"fileName,omitempty"`
	StartingOffset       string   `protobuf:"bytes,7,opt,name=startingOffset,proto3" json:"startingOffset,omitempty"`
	DataLength           string   `protobuf:"bytes,8,opt,name=dataLength,proto3" json:"dataLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromRequest) Reset()         { *m = CopyFromRequest{} }
func (m *CopyFromRequest) String() string { return proto.CompactTextString(m) }
func (*CopyFromRequest) ProtoMessage()    {}
func (*CopyFromRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{11}
}
func (m *CopyFromRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromRequest.Unmarshal(m, b)
}
func (m *CopyFromRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromRequest.Marshal(b, m, deterministic)
}
func (dst *CopyFromRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromRequest.Merge(dst, src)
}
func (m *CopyFromRequest) XXX_Size() int {
	return xxx_messageInfo_CopyFromRequest.Size(m)
}
func (m *CopyFromRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromRequest proto.InternalMessageInfo

func (m *CopyFromRequest) GetSourceServerName() string {
	if m != nil {
		return m.SourceServerName
	}
	return ""
}

func (m *CopyFromRequest) GetSoucePartitionUuid() string {
	if m != nil {
		return m.SoucePartitionUuid
	}
	return ""
}

func (m *CopyFromRequest) GetSourceFileName() string {
	if m != nil {
		return m.SourceFileName
	}
	return ""
}

func (m *CopyFromRequest) GetSourceStartingOffset() string {
	if m != nil {
		return m.SourceStartingOffset
	}
	return ""
}

func (m *CopyFromRequest) GetPartitionUuid() string {
	if m != nil {
		return m.PartitionUuid
	}
	return ""
}

func (m *CopyFromRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CopyFromRequest) GetStartingOffset() string {
	if m != nil {
		return m.StartingOffset
	}
	return ""
}

func (m *CopyFromRequest) GetDataLength() string {
	if m != nil {
		return m.DataLength
	}
	return ""
}

type CopyFromResponse struct {
	DataCheckSum         []byte   `protobuf:"bytes,1,opt,name=dataCheckSum,proto3" json:"dataCheckSum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromResponse) Reset()         { *m = CopyFromResponse{} }
func (m *CopyFromResponse) String() string { return proto.CompactTextString(m) }
func (*CopyFromResponse) ProtoMessage()    {}
func (*CopyFromResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{12}
}
func (m *CopyFromResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromResponse.Unmarshal(m, b)
}
func (m *CopyFromResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromResponse.Marshal(b, m, deterministic)
}
func (dst *CopyFromResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromResponse.Merge(dst, src)
}
func (m *CopyFromResponse) XXX_Size() int {
	return xxx_messageInfo_CopyFromResponse.Size(m)
}
func (m *CopyFromResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromResponse proto.InternalMessageInfo

func (m *CopyFromResponse) GetDataCheckSum() []byte {
	if m != nil {
		return m.DataCheckSum
	}
	return nil
}

type SetConfigurationRequest struct {
	// change id
	StorageServerId string `protobuf:"bytes,1,opt,name=storageServerId,proto3" json:"storageServerId,omitempty"`
	// change default blockbin byte size
	DefaultBlockBinSizeBytes int64    `protobuf:"varint,2,opt,name=defaultBlockBinSizeBytes,proto3" json:"defaultBlockBinSizeBytes,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *SetConfigurationRequest) Reset()         { *m = SetConfigurationRequest{} }
func (m *SetConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigurationRequest) ProtoMessage()    {}
func (*SetConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{13}
}
func (m *SetConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigurationRequest.Unmarshal(m, b)
}
func (m *SetConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigurationRequest.Marshal(b, m, deterministic)
}
func (dst *SetConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigurationRequest.Merge(dst, src)
}
func (m *SetConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigurationRequest.Size(m)
}
func (m *SetConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigurationRequest proto.InternalMessageInfo

func (m *SetConfigurationRequest) GetStorageServerId() string {
	if m != nil {
		return m.StorageServerId
	}
	return ""
}

func (m *SetConfigurationRequest) GetDefaultBlockBinSizeBytes() int64 {
	if m != nil {
		return m.DefaultBlockBinSizeBytes
	}
	return 0
}

type SetConfigurationResponse struct {
	Configuration        *Configuration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetConfigurationResponse) Reset()         { *m = SetConfigurationResponse{} }
func (m *SetConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigurationResponse) ProtoMessage()    {}
func (*SetConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{14}
}
func (m *SetConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigurationResponse.Unmarshal(m, b)
}
func (m *SetConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigurationResponse.Marshal(b, m, deterministic)
}
func (dst *SetConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigurationResponse.Merge(dst, src)
}
func (m *SetConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigurationResponse.Size(m)
}
func (m *SetConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigurationResponse proto.InternalMessageInfo

func (m *SetConfigurationResponse) GetConfiguration() *Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type ConfigurationRequest struct {
	SsdConfigurationRequest []*ConfigurationRequestForSSD `protobuf:"bytes,1,rep,name=ssdConfigurationRequest,proto3" json:"ssdConfigurationRequest,omitempty"`
	Level                   int32                         `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	HighestLevel            int32                         `protobuf:"varint,3,opt,name=highestLevel,proto3" json:"highestLevel,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                      `json:"-"`
	XXX_unrecognized        []byte                        `json:"-"`
	XXX_sizecache           int32                         `json:"-"`
}

func (m *ConfigurationRequest) Reset()         { *m = ConfigurationRequest{} }
func (m *ConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigurationRequest) ProtoMessage()    {}
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{15}
}
func (m *ConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationRequest.Unmarshal(m, b)
}
func (m *ConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationRequest.Marshal(b, m, deterministic)
}
func (dst *ConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationRequest.Merge(dst, src)
}
func (m *ConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigurationRequest.Size(m)
}
func (m *ConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationRequest proto.InternalMessageInfo

func (m *ConfigurationRequest) GetSsdConfigurationRequest() []*ConfigurationRequestForSSD {
	if m != nil {
		return m.SsdConfigurationRequest
	}
	return nil
}

func (m *ConfigurationRequest) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ConfigurationRequest) GetHighestLevel() int32 {
	if m != nil {
		return m.HighestLevel
	}
	return 0
}

type ConfigurationRequestForSSD struct {
	SsdId                   string     `protobuf:"bytes,1,opt,name=ssdId,proto3" json:"ssdId,omitempty"`
	RequestInvalidatedCache bool       `protobuf:"varint,2,opt,name=requestInvalidatedCache,proto3" json:"requestInvalidatedCache,omitempty"`
	NotifiedLocations       *Locations `protobuf:"bytes,3,opt,name=notifiedLocations,proto3" json:"notifiedLocations,omitempty"`
	Token                   *Location  `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}   `json:"-"`
	XXX_unrecognized        []byte     `json:"-"`
	XXX_sizecache           int32      `json:"-"`
}

func (m *ConfigurationRequestForSSD) Reset()         { *m = ConfigurationRequestForSSD{} }
func (m *ConfigurationRequestForSSD) String() string { return proto.CompactTextString(m) }
func (*ConfigurationRequestForSSD) ProtoMessage()    {}
func (*ConfigurationRequestForSSD) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{16}
}
func (m *ConfigurationRequestForSSD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationRequestForSSD.Unmarshal(m, b)
}
func (m *ConfigurationRequestForSSD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationRequestForSSD.Marshal(b, m, deterministic)
}
func (dst *ConfigurationRequestForSSD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationRequestForSSD.Merge(dst, src)
}
func (m *ConfigurationRequestForSSD) XXX_Size() int {
	return xxx_messageInfo_ConfigurationRequestForSSD.Size(m)
}
func (m *ConfigurationRequestForSSD) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationRequestForSSD.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationRequestForSSD proto.InternalMessageInfo

func (m *ConfigurationRequestForSSD) GetSsdId() string {
	if m != nil {
		return m.SsdId
	}
	return ""
}

func (m *ConfigurationRequestForSSD) GetRequestInvalidatedCache() bool {
	if m != nil {
		return m.RequestInvalidatedCache
	}
	return false
}

func (m *ConfigurationRequestForSSD) GetNotifiedLocations() *Locations {
	if m != nil {
		return m.NotifiedLocations
	}
	return nil
}

func (m *ConfigurationRequestForSSD) GetToken() *Location {
	if m != nil {
		return m.Token
	}
	return nil
}

type ConfigurationResponse struct {
	Configuration        *Configuration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigurationResponse) Reset()         { *m = ConfigurationResponse{} }
func (m *ConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigurationResponse) ProtoMessage()    {}
func (*ConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{17}
}
func (m *ConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationResponse.Unmarshal(m, b)
}
func (m *ConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationResponse.Merge(dst, src)
}
func (m *ConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigurationResponse.Size(m)
}
func (m *ConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationResponse proto.InternalMessageInfo

func (m *ConfigurationResponse) GetConfiguration() *Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type Configuration struct {
	StorageServerId          string           `protobuf:"bytes,1,opt,name=storageServerId,proto3" json:"storageServerId,omitempty"`
	SyslogEnabled            bool             `protobuf:"varint,2,opt,name=syslogEnabled,proto3" json:"syslogEnabled,omitempty"`
	SyslogFlags              string           `protobuf:"bytes,3,opt,name=syslogFlags,proto3" json:"syslogFlags,omitempty"`
	DefaultBlockBinSizeBytes int64            `protobuf:"varint,4,opt,name=defaultBlockBinSizeBytes,proto3" json:"defaultBlockBinSizeBytes,omitempty"`
	Status                   *Status          `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Partition                []*PartitionInfo `protobuf:"bytes,6,rep,name=partition,proto3" json:"partition,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}         `json:"-"`
	XXX_unrecognized         []byte           `json:"-"`
	XXX_sizecache            int32            `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{18}
}
func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (dst *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(dst, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetStorageServerId() string {
	if m != nil {
		return m.StorageServerId
	}
	return ""
}

func (m *Configuration) GetSyslogEnabled() bool {
	if m != nil {
		return m.SyslogEnabled
	}
	return false
}

func (m *Configuration) GetSyslogFlags() string {
	if m != nil {
		return m.SyslogFlags
	}
	return ""
}

func (m *Configuration) GetDefaultBlockBinSizeBytes() int64 {
	if m != nil {
		return m.DefaultBlockBinSizeBytes
	}
	return 0
}

func (m *Configuration) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Configuration) GetPartition() []*PartitionInfo {
	if m != nil {
		return m.Partition
	}
	return nil
}

type Location struct {
	PartitionId          string   `protobuf:"bytes,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	BlockBinId           string   `protobuf:"bytes,2,opt,name=blockBinId,proto3" json:"blockBinId,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{19}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetPartitionId() string {
	if m != nil {
		return m.PartitionId
	}
	return ""
}

func (m *Location) GetBlockBinId() string {
	if m != nil {
		return m.BlockBinId
	}
	return ""
}

func (m *Location) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Location) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Locations struct {
	Location             []*Location `protobuf:"bytes,1,rep,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Locations) Reset()         { *m = Locations{} }
func (m *Locations) String() string { return proto.CompactTextString(m) }
func (*Locations) ProtoMessage()    {}
func (*Locations) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{20}
}
func (m *Locations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Locations.Unmarshal(m, b)
}
func (m *Locations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Locations.Marshal(b, m, deterministic)
}
func (dst *Locations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Locations.Merge(dst, src)
}
func (m *Locations) XXX_Size() int {
	return xxx_messageInfo_Locations.Size(m)
}
func (m *Locations) XXX_DiscardUnknown() {
	xxx_messageInfo_Locations.DiscardUnknown(m)
}

var xxx_messageInfo_Locations proto.InternalMessageInfo

func (m *Locations) GetLocation() []*Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type PartitionInfo struct {
	Uuid                 string                        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Path                 string                        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	State                PartitionInfo_PartitionState  `protobuf:"varint,3,opt,name=state,proto3,enum=storageserver.PartitionInfo_PartitionState" json:"state,omitempty"`
	ErrorMessage         string                        `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	SizeBytes            int64                         `protobuf:"varint,5,opt,name=sizeBytes,proto3" json:"sizeBytes,omitempty"`
	AvailableBytes       int64                         `protobuf:"varint,6,opt,name=availableBytes,proto3" json:"availableBytes,omitempty"`
	BlockBinInfo         []*PartitionInfo_BlockBinInfo `protobuf:"bytes,7,rep,name=blockBinInfo,proto3" json:"blockBinInfo,omitempty"`
	SerialNumber         string                        `protobuf:"bytes,8,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	Slot                 string                        `protobuf:"bytes,9,opt,name=slot,proto3" json:"slot,omitempty"`
	Device               string                        `protobuf:"bytes,10,opt,name=device,proto3" json:"device,omitempty"`
	IsSSD                bool                          `protobuf:"varint,11,opt,name=isSSD,proto3" json:"isSSD,omitempty"`
	Locations            *Locations                    `protobuf:"bytes,12,opt,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PartitionInfo) Reset()         { *m = PartitionInfo{} }
func (m *PartitionInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionInfo) ProtoMessage()    {}
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{21}
}
func (m *PartitionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionInfo.Unmarshal(m, b)
}
func (m *PartitionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionInfo.Marshal(b, m, deterministic)
}
func (dst *PartitionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionInfo.Merge(dst, src)
}
func (m *PartitionInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionInfo.Size(m)
}
func (m *PartitionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionInfo proto.InternalMessageInfo

func (m *PartitionInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PartitionInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PartitionInfo) GetState() PartitionInfo_PartitionState {
	if m != nil {
		return m.State
	}
	return PartitionInfo_UNKNOWN
}

func (m *PartitionInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *PartitionInfo) GetSizeBytes() int64 {
	if m != nil {
		return m.SizeBytes
	}
	return 0
}

func (m *PartitionInfo) GetAvailableBytes() int64 {
	if m != nil {
		return m.AvailableBytes
	}
	return 0
}

func (m *PartitionInfo) GetBlockBinInfo() []*PartitionInfo_BlockBinInfo {
	if m != nil {
		return m.BlockBinInfo
	}
	return nil
}

func (m *PartitionInfo) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *PartitionInfo) GetSlot() string {
	if m != nil {
		return m.Slot
	}
	return ""
}

func (m *PartitionInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *PartitionInfo) GetIsSSD() bool {
	if m != nil {
		return m.IsSSD
	}
	return false
}

func (m *PartitionInfo) GetLocations() *Locations {
	if m != nil {
		return m.Locations
	}
	return nil
}

type PartitionInfo_BlockBinInfo struct {
	Id                   string                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size                 int64                                    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	State                PartitionInfo_BlockBinInfo_BlockBinState `protobuf:"varint,3,opt,name=state,proto3,enum=storageserver.PartitionInfo_BlockBinInfo_BlockBinState" json:"state,omitempty"`
	ErrorMessage         string                                   `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *PartitionInfo_BlockBinInfo) Reset()         { *m = PartitionInfo_BlockBinInfo{} }
func (m *PartitionInfo_BlockBinInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionInfo_BlockBinInfo) ProtoMessage()    {}
func (*PartitionInfo_BlockBinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{21, 0}
}
func (m *PartitionInfo_BlockBinInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionInfo_BlockBinInfo.Unmarshal(m, b)
}
func (m *PartitionInfo_BlockBinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionInfo_BlockBinInfo.Marshal(b, m, deterministic)
}
func (dst *PartitionInfo_BlockBinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionInfo_BlockBinInfo.Merge(dst, src)
}
func (m *PartitionInfo_BlockBinInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionInfo_BlockBinInfo.Size(m)
}
func (m *PartitionInfo_BlockBinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionInfo_BlockBinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionInfo_BlockBinInfo proto.InternalMessageInfo

func (m *PartitionInfo_BlockBinInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PartitionInfo_BlockBinInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PartitionInfo_BlockBinInfo) GetState() PartitionInfo_BlockBinInfo_BlockBinState {
	if m != nil {
		return m.State
	}
	return PartitionInfo_BlockBinInfo_ONLINE
}

func (m *PartitionInfo_BlockBinInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{22}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	StorageServerId      string   `protobuf:"bytes,1,opt,name=storageServerId,proto3" json:"storageServerId,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ChangeId             int64    `protobuf:"varint,3,opt,name=changeId,proto3" json:"changeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{23}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStorageServerId() string {
	if m != nil {
		return m.StorageServerId
	}
	return ""
}

func (m *StatusResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StatusResponse) GetChangeId() int64 {
	if m != nil {
		return m.ChangeId
	}
	return 0
}

type Status struct {
	ServerStartTime      string   `protobuf:"bytes,1,opt,name=serverStartTime,proto3" json:"serverStartTime,omitempty"`
	RequestCount         int64    `protobuf:"varint,2,opt,name=requestCount,proto3" json:"requestCount,omitempty"`
	RequestErrorCount    int64    `protobuf:"varint,3,opt,name=requestErrorCount,proto3" json:"requestErrorCount,omitempty"`
	PartitionCount       int64    `protobuf:"varint,4,opt,name=partitionCount,proto3" json:"partitionCount,omitempty"`
	PartitionError       int64    `protobuf:"varint,5,opt,name=partitionError,proto3" json:"partitionError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{24}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetServerStartTime() string {
	if m != nil {
		return m.ServerStartTime
	}
	return ""
}

func (m *Status) GetRequestCount() int64 {
	if m != nil {
		return m.RequestCount
	}
	return 0
}

func (m *Status) GetRequestErrorCount() int64 {
	if m != nil {
		return m.RequestErrorCount
	}
	return 0
}

func (m *Status) GetPartitionCount() int64 {
	if m != nil {
		return m.PartitionCount
	}
	return 0
}

func (m *Status) GetPartitionError() int64 {
	if m != nil {
		return m.PartitionError
	}
	return 0
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{25}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type IOStats struct {
	AverageReadRequestTime    uint64   `protobuf:"varint,1,opt,name=averageReadRequestTime,proto3" json:"averageReadRequestTime,omitempty"`
	AverageWriteRequestTime   uint64   `protobuf:"varint,2,opt,name=averageWriteRequestTime,proto3" json:"averageWriteRequestTime,omitempty"`
	EstimatedReadRequestTime  uint64   `protobuf:"varint,3,opt,name=estimatedReadRequestTime,proto3" json:"estimatedReadRequestTime,omitempty"`
	EstimatedWriteRequestTime uint64   `protobuf:"varint,4,opt,name=estimatedWriteRequestTime,proto3" json:"estimatedWriteRequestTime,omitempty"`
	ReadOperations            uint64   `protobuf:"varint,5,opt,name=readOperations,proto3" json:"readOperations,omitempty"`
	WriteOperations           uint64   `protobuf:"varint,6,opt,name=writeOperations,proto3" json:"writeOperations,omitempty"`
	AverageReadTime           uint64   `protobuf:"varint,7,opt,name=averageReadTime,proto3" json:"averageReadTime,omitempty"`
	AverageWriteTime          uint64   `protobuf:"varint,8,opt,name=averageWriteTime,proto3" json:"averageWriteTime,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *IOStats) Reset()         { *m = IOStats{} }
func (m *IOStats) String() string { return proto.CompactTextString(m) }
func (*IOStats) ProtoMessage()    {}
func (*IOStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{26}
}
func (m *IOStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IOStats.Unmarshal(m, b)
}
func (m *IOStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IOStats.Marshal(b, m, deterministic)
}
func (dst *IOStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOStats.Merge(dst, src)
}
func (m *IOStats) XXX_Size() int {
	return xxx_messageInfo_IOStats.Size(m)
}
func (m *IOStats) XXX_DiscardUnknown() {
	xxx_messageInfo_IOStats.DiscardUnknown(m)
}

var xxx_messageInfo_IOStats proto.InternalMessageInfo

func (m *IOStats) GetAverageReadRequestTime() uint64 {
	if m != nil {
		return m.AverageReadRequestTime
	}
	return 0
}

func (m *IOStats) GetAverageWriteRequestTime() uint64 {
	if m != nil {
		return m.AverageWriteRequestTime
	}
	return 0
}

func (m *IOStats) GetEstimatedReadRequestTime() uint64 {
	if m != nil {
		return m.EstimatedReadRequestTime
	}
	return 0
}

func (m *IOStats) GetEstimatedWriteRequestTime() uint64 {
	if m != nil {
		return m.EstimatedWriteRequestTime
	}
	return 0
}

func (m *IOStats) GetReadOperations() uint64 {
	if m != nil {
		return m.ReadOperations
	}
	return 0
}

func (m *IOStats) GetWriteOperations() uint64 {
	if m != nil {
		return m.WriteOperations
	}
	return 0
}

func (m *IOStats) GetAverageReadTime() uint64 {
	if m != nil {
		return m.AverageReadTime
	}
	return 0
}

func (m *IOStats) GetAverageWriteTime() uint64 {
	if m != nil {
		return m.AverageWriteTime
	}
	return 0
}

type PartitionStats struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Stats                *IOStats `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionStats) Reset()         { *m = PartitionStats{} }
func (m *PartitionStats) String() string { return proto.CompactTextString(m) }
func (*PartitionStats) ProtoMessage()    {}
func (*PartitionStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{27}
}
func (m *PartitionStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionStats.Unmarshal(m, b)
}
func (m *PartitionStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionStats.Marshal(b, m, deterministic)
}
func (dst *PartitionStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionStats.Merge(dst, src)
}
func (m *PartitionStats) XXX_Size() int {
	return xxx_messageInfo_PartitionStats.Size(m)
}
func (m *PartitionStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionStats.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionStats proto.InternalMessageInfo

func (m *PartitionStats) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PartitionStats) GetStats() *IOStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type PingResponse struct {
	PartitionStats       []*PartitionStats `protobuf:"bytes,1,rep,name=partitionStats,proto3" json:"partitionStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{28}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (dst *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(dst, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetPartitionStats() []*PartitionStats {
	if m != nil {
		return m.PartitionStats
	}
	return nil
}

type Event struct {
	EventId              int64          `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventMessage         int64          `protobuf:"varint,2,opt,name=eventMessage,proto3" json:"eventMessage,omitempty"`
	DateTime             string         `protobuf:"bytes,3,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Severity             Event_Severity `protobuf:"varint,4,opt,name=severity,proto3,enum=storageserver.Event_Severity" json:"severity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{29}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *Event) GetEventMessage() int64 {
	if m != nil {
		return m.EventMessage
	}
	return 0
}

func (m *Event) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *Event) GetSeverity() Event_Severity {
	if m != nil {
		return m.Severity
	}
	return Event_INFORMATIONAL
}

type EventRequest struct {
	StorageServerId      string   `protobuf:"bytes,1,opt,name=storageServerId,proto3" json:"storageServerId,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{30}
}
func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (dst *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(dst, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetStorageServerId() string {
	if m != nil {
		return m.StorageServerId
	}
	return ""
}

func (m *EventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type ConnectionPoolRequest struct {
	PoolId               string   `protobuf:"bytes,1,opt,name=poolId,proto3" json:"poolId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionPoolRequest) Reset()         { *m = ConnectionPoolRequest{} }
func (m *ConnectionPoolRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolRequest) ProtoMessage()    {}
func (*ConnectionPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{31}
}
func (m *ConnectionPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPoolRequest.Unmarshal(m, b)
}
func (m *ConnectionPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPoolRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectionPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPoolRequest.Merge(dst, src)
}
func (m *ConnectionPoolRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionPoolRequest.Size(m)
}
func (m *ConnectionPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPoolRequest proto.InternalMessageInfo

func (m *ConnectionPoolRequest) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

type ConnectionPoolResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionPoolResponse) Reset()         { *m = ConnectionPoolResponse{} }
func (m *ConnectionPoolResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolResponse) ProtoMessage()    {}
func (*ConnectionPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{32}
}
func (m *ConnectionPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPoolResponse.Unmarshal(m, b)
}
func (m *ConnectionPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPoolResponse.Marshal(b, m, deterministic)
}
func (dst *ConnectionPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPoolResponse.Merge(dst, src)
}
func (m *ConnectionPoolResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionPoolResponse.Size(m)
}
func (m *ConnectionPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPoolResponse proto.InternalMessageInfo

type Entry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{33}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MgmtRequest struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Parameters           []*Entry `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtRequest) Reset()         { *m = MgmtRequest{} }
func (m *MgmtRequest) String() string { return proto.CompactTextString(m) }
func (*MgmtRequest) ProtoMessage()    {}
func (*MgmtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{34}
}
func (m *MgmtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtRequest.Unmarshal(m, b)
}
func (m *MgmtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtRequest.Marshal(b, m, deterministic)
}
func (dst *MgmtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtRequest.Merge(dst, src)
}
func (m *MgmtRequest) XXX_Size() int {
	return xxx_messageInfo_MgmtRequest.Size(m)
}
func (m *MgmtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtRequest proto.InternalMessageInfo

func (m *MgmtRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *MgmtRequest) GetParameters() []*Entry {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type MgmtResponse struct {
	Results              []*Entry `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtResponse) Reset()         { *m = MgmtResponse{} }
func (m *MgmtResponse) String() string { return proto.CompactTextString(m) }
func (*MgmtResponse) ProtoMessage()    {}
func (*MgmtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_a602039b6a174dd7, []int{35}
}
func (m *MgmtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtResponse.Unmarshal(m, b)
}
func (m *MgmtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtResponse.Marshal(b, m, deterministic)
}
func (dst *MgmtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtResponse.Merge(dst, src)
}
func (m *MgmtResponse) XXX_Size() int {
	return xxx_messageInfo_MgmtResponse.Size(m)
}
func (m *MgmtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtResponse proto.InternalMessageInfo

func (m *MgmtResponse) GetResults() []*Entry {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "storageserver.Request")
	proto.RegisterType((*Response)(nil), "storageserver.Response")
	proto.RegisterType((*RequestMetadata)(nil), "storageserver.RequestMetadata")
	proto.RegisterType((*SyncBlockBinRequest)(nil), "storageserver.SyncBlockBinRequest")
	proto.RegisterType((*SyncBlockBinResponse)(nil), "storageserver.SyncBlockBinResponse")
	proto.RegisterType((*WriteRequest)(nil), "storageserver.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "storageserver.WriteResponse")
	proto.RegisterType((*ReadRequest)(nil), "storageserver.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "storageserver.ReadResponse")
	proto.RegisterType((*VerifyDataRequest)(nil), "storageserver.VerifyDataRequest")
	proto.RegisterType((*VerifyDataResponse)(nil), "storageserver.VerifyDataResponse")
	proto.RegisterType((*CopyFromRequest)(nil), "storageserver.CopyFromRequest")
	proto.RegisterType((*CopyFromResponse)(nil), "storageserver.CopyFromResponse")
	proto.RegisterType((*SetConfigurationRequest)(nil), "storageserver.SetConfigurationRequest")
	proto.RegisterType((*SetConfigurationResponse)(nil), "storageserver.SetConfigurationResponse")
	proto.RegisterType((*ConfigurationRequest)(nil), "storageserver.ConfigurationRequest")
	proto.RegisterType((*ConfigurationRequestForSSD)(nil), "storageserver.ConfigurationRequestForSSD")
	proto.RegisterType((*ConfigurationResponse)(nil), "storageserver.ConfigurationResponse")
	proto.RegisterType((*Configuration)(nil), "storageserver.Configuration")
	proto.RegisterType((*Location)(nil), "storageserver.Location")
	proto.RegisterType((*Locations)(nil), "storageserver.Locations")
	proto.RegisterType((*PartitionInfo)(nil), "storageserver.PartitionInfo")
	proto.RegisterType((*PartitionInfo_BlockBinInfo)(nil), "storageserver.PartitionInfo.BlockBinInfo")
	proto.RegisterType((*StatusRequest)(nil), "storageserver.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "storageserver.StatusResponse")
	proto.RegisterType((*Status)(nil), "storageserver.Status")
	proto.RegisterType((*PingRequest)(nil), "storageserver.PingRequest")
	proto.RegisterType((*IOStats)(nil), "storageserver.IOStats")
	proto.RegisterType((*PartitionStats)(nil), "storageserver.PartitionStats")
	proto.RegisterType((*PingResponse)(nil), "storageserver.PingResponse")
	proto.RegisterType((*Event)(nil), "storageserver.Event")
	proto.RegisterType((*EventRequest)(nil), "storageserver.EventRequest")
	proto.RegisterType((*ConnectionPoolRequest)(nil), "storageserver.ConnectionPoolRequest")
	proto.RegisterType((*ConnectionPoolResponse)(nil), "storageserver.ConnectionPoolResponse")
	proto.RegisterType((*Entry)(nil), "storageserver.Entry")
	proto.RegisterType((*MgmtRequest)(nil), "storageserver.MgmtRequest")
	proto.RegisterType((*MgmtResponse)(nil), "storageserver.MgmtResponse")
	proto.RegisterEnum("storageserver.Response_Status", Response_Status_name, Response_Status_value)
	proto.RegisterEnum("storageserver.PartitionInfo_PartitionState", PartitionInfo_PartitionState_name, PartitionInfo_PartitionState_value)
	proto.RegisterEnum("storageserver.PartitionInfo_BlockBinInfo_BlockBinState", PartitionInfo_BlockBinInfo_BlockBinState_name, PartitionInfo_BlockBinInfo_BlockBinState_value)
	proto.RegisterEnum("storageserver.Event_Severity", Event_Severity_name, Event_Severity_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SsClient is the client API for Ss service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SsClient interface {
	Ping(ctx context.Context, opts ...grpc.CallOption) (Ss_PingClient, error)
	Read(ctx context.Context, opts ...grpc.CallOption) (Ss_ReadClient, error)
}

type ssClient struct {
	cc *grpc.ClientConn
}

func NewSsClient(cc *grpc.ClientConn) SsClient {
	return &ssClient{cc}
}

func (c *ssClient) Ping(ctx context.Context, opts ...grpc.CallOption) (Ss_PingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Ss_serviceDesc.Streams[0], "/storageserver.Ss/Ping", opts...)
	if err != nil {
		return nil, err
	}
	x := &ssPingClient{stream}
	return x, nil
}

type Ss_PingClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type ssPingClient struct {
	grpc.ClientStream
}

func (x *ssPingClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ssPingClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ssClient) Read(ctx context.Context, opts ...grpc.CallOption) (Ss_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Ss_serviceDesc.Streams[1], "/storageserver.Ss/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &ssReadClient{stream}
	return x, nil
}

type Ss_ReadClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type ssReadClient struct {
	grpc.ClientStream
}

func (x *ssReadClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ssReadClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SsServer is the server API for Ss service.
type SsServer interface {
	Ping(Ss_PingServer) error
	Read(Ss_ReadServer) error
}

func RegisterSsServer(s *grpc.Server, srv SsServer) {
	s.RegisterService(&_Ss_serviceDesc, srv)
}

func _Ss_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SsServer).Ping(&ssPingServer{stream})
}

type Ss_PingServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type ssPingServer struct {
	grpc.ServerStream
}

func (x *ssPingServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ssPingServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Ss_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SsServer).Read(&ssReadServer{stream})
}

type Ss_ReadServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type ssReadServer struct {
	grpc.ServerStream
}

func (x *ssReadServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ssReadServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ss_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storageserver.Ss",
	HandlerType: (*SsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _Ss_Ping_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _Ss_Read_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_a602039b6a174dd7) }

var fileDescriptor_storage_a602039b6a174dd7 = []byte{
	// 1892 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x5f, 0x8f, 0x23, 0x47,
	0x11, 0xbf, 0xf1, 0x7f, 0x97, 0xed, 0x5d, 0x5f, 0xb3, 0xb7, 0x3b, 0xac, 0x42, 0xb4, 0x6a, 0x45,
	0x91, 0x09, 0x39, 0x07, 0x6d, 0xd0, 0x11, 0x8e, 0x7f, 0xf1, 0xfa, 0xbc, 0x60, 0x58, 0xdb, 0xa7,
	0x9e, 0xdb, 0x9c, 0x10, 0x02, 0x34, 0x37, 0x6e, 0xdb, 0xa3, 0x1d, 0x4f, 0x9b, 0xe9, 0xb1, 0x89,
	0x79, 0x01, 0x45, 0xf0, 0x09, 0x78, 0xce, 0x3b, 0x5f, 0x00, 0x89, 0x2f, 0xc1, 0x53, 0xf8, 0x06,
	0xbc, 0xf0, 0x0d, 0x78, 0x45, 0xfd, 0x67, 0xc6, 0x33, 0x63, 0x7b, 0xff, 0x20, 0x22, 0xe5, 0xad,
	0xab, 0xba, 0xaa, 0xab, 0xea, 0x57, 0xd5, 0x55, 0xd3, 0x03, 0x0d, 0x1e, 0xb2, 0xc0, 0x9e, 0xd2,
	0xf6, 0x22, 0x60, 0x21, 0x43, 0x11, 0xc9, 0x69, 0xb0, 0xa2, 0x01, 0xfe, 0x63, 0x0e, 0xca, 0x84,
	0xfe, 0x76, 0x49, 0x79, 0x88, 0x4c, 0x28, 0xaf, 0x68, 0xc0, 0x5d, 0xe6, 0x9b, 0xc6, 0x99, 0xd1,
	0xca, 0x93, 0x88, 0x44, 0x2d, 0x38, 0x9c, 0x53, 0xce, 0xed, 0x29, 0xed, 0xce, 0xa8, 0x73, 0x63,
	0x2d, 0xe7, 0x66, 0xee, 0xcc, 0x68, 0xd5, 0x49, 0x96, 0x2d, 0xce, 0x70, 0x98, 0x1f, 0xd2, 0x4f,
	0x43, 0x33, 0x2f, 0x25, 0x22, 0x12, 0xbd, 0x05, 0xd5, 0x40, 0x19, 0xea, 0x8f, 0xcd, 0xc2, 0x99,
	0xd1, 0xaa, 0x92, 0x0d, 0x03, 0x1d, 0x43, 0x89, 0x05, 0xee, 0xd4, 0xf5, 0xcd, 0xa2, 0xdc, 0xd2,
	0x94, 0x38, 0x2f, 0x74, 0xe7, 0x94, 0x2d, 0x43, 0xb3, 0x74, 0x66, 0xb4, 0x0a, 0x24, 0x22, 0xd1,
	0x8f, 0xa1, 0xb6, 0x70, 0xfd, 0xa9, 0x76, 0xde, 0xfc, 0x77, 0xf9, 0xcc, 0x68, 0xd5, 0xce, 0x4f,
	0xdb, 0xa9, 0xf8, 0xda, 0x2f, 0x37, 0x22, 0x3f, 0x7d, 0x44, 0x92, 0x1a, 0x17, 0x25, 0x28, 0x88,
	0x5d, 0xfc, 0xa7, 0x1c, 0x54, 0x08, 0xe5, 0x0b, 0xe6, 0x73, 0x7a, 0x0b, 0x06, 0xcf, 0xa0, 0xc4,
	0x43, 0x3b, 0x5c, 0x72, 0x19, 0xfa, 0xc1, 0xf9, 0xdb, 0x19, 0x4b, 0xd1, 0x11, 0x6d, 0x4b, 0x4a,
	0x11, 0x2d, 0xbd, 0x0b, 0xbb, 0xfc, 0x6e, 0xec, 0x30, 0xd4, 0x69, 0x10, 0xb0, 0x60, 0xa0, 0xf8,
	0x1a, 0xa4, 0x14, 0x2f, 0x89, 0x6f, 0xf1, 0x16, 0x7c, 0x4b, 0x19, 0x7c, 0xf1, 0x19, 0x94, 0x94,
	0x5f, 0xa8, 0x06, 0x65, 0xeb, 0xba, 0xdb, 0xed, 0x59, 0x56, 0xf3, 0x11, 0xaa, 0x42, 0xb1, 0x47,
	0xc8, 0x88, 0x34, 0x0d, 0xcc, 0xe1, 0x50, 0x23, 0x33, 0xa0, 0xa1, 0x3d, 0xb6, 0x43, 0x5b, 0x1c,
	0xe9, 0xcc, 0x96, 0xfe, 0x8d, 0xe5, 0xfe, 0x9e, 0x4a, 0x38, 0x1a, 0x64, 0xc3, 0x40, 0x67, 0x50,
	0x93, 0xc4, 0x68, 0x32, 0xe1, 0x34, 0x94, 0xa8, 0x14, 0x48, 0x92, 0x25, 0x24, 0xf8, 0x8c, 0x2d,
	0xbd, 0x71, 0xd7, 0x76, 0x66, 0x54, 0x86, 0x5d, 0x21, 0x49, 0x16, 0xfe, 0x8b, 0x01, 0x5f, 0xb3,
	0xd6, 0xbe, 0x73, 0xe1, 0x31, 0xe7, 0xe6, 0xc2, 0xf5, 0xa3, 0x52, 0x7c, 0x07, 0x1a, 0x0b, 0x3b,
	0x08, 0xdd, 0xd0, 0x65, 0xfe, 0xf5, 0xd2, 0x1d, 0x4b, 0xeb, 0x55, 0x92, 0x66, 0xa2, 0x53, 0xa8,
	0x4c, 0x5c, 0x8f, 0x0e, 0xed, 0x39, 0x95, 0xe6, 0xab, 0x24, 0xa6, 0xd1, 0x73, 0xa8, 0xcc, 0x75,
	0x1c, 0xd2, 0x70, 0x6d, 0x47, 0xc2, 0x52, 0xd1, 0x92, 0x58, 0x1e, 0x7f, 0x0c, 0x47, 0x69, 0xa7,
	0x74, 0x71, 0xb4, 0xe0, 0x50, 0xe9, 0x5a, 0xa1, 0x1d, 0x84, 0xaf, 0xdc, 0x39, 0xd5, 0x7e, 0x65,
	0xd9, 0xf8, 0xef, 0x39, 0xa8, 0xbf, 0x0e, 0xdc, 0x90, 0xfe, 0xff, 0x02, 0x7a, 0x17, 0x0e, 0xb8,
	0x38, 0xdf, 0xf5, 0xa7, 0x1a, 0xf1, 0xbc, 0x2c, 0xd0, 0x0c, 0x17, 0xbd, 0x0d, 0x20, 0x82, 0xb8,
	0xa2, 0xfe, 0x34, 0x9c, 0xc9, 0x1a, 0xca, 0x93, 0x04, 0x47, 0x26, 0x65, 0xed, 0x3b, 0x23, 0x5f,
	0xfa, 0x27, 0xab, 0x48, 0x24, 0x65, 0xc3, 0x12, 0x75, 0x28, 0xe4, 0xe3, 0x72, 0x2d, 0xc9, 0x42,
	0x4b, 0xf1, 0x44, 0x69, 0xf0, 0x1b, 0x77, 0xa1, 0xce, 0x28, 0xcb, 0x33, 0x36, 0x8c, 0x14, 0xf8,
	0x95, 0x07, 0x82, 0xff, 0x2b, 0x68, 0x68, 0xe4, 0x34, 0xea, 0x59, 0x77, 0x8c, 0x1d, 0xee, 0xec,
	0xc8, 0x4c, 0x6e, 0x77, 0x66, 0xbe, 0x30, 0xa0, 0x46, 0xa8, 0x3d, 0xfe, 0xea, 0x25, 0x26, 0x09,
	0x5a, 0xf1, 0x81, 0xa0, 0xb5, 0xa1, 0xae, 0x82, 0xd2, 0x98, 0xa5, 0x6d, 0x19, 0x59, 0x5b, 0xf8,
	0x73, 0x03, 0x1e, 0x7f, 0x42, 0x03, 0x77, 0xb2, 0x7e, 0x21, 0x0e, 0xfa, 0xaa, 0x61, 0x81, 0x3f,
	0x02, 0x94, 0x74, 0xef, 0xfe, 0x95, 0x80, 0xbf, 0xc8, 0xc1, 0x61, 0x97, 0x2d, 0xd6, 0x97, 0x01,
	0x9b, 0x47, 0x71, 0xbd, 0x07, 0x4d, 0xce, 0x96, 0x81, 0x43, 0x2d, 0x89, 0xa3, 0xf4, 0x5c, 0x85,
	0xb6, 0xc5, 0x47, 0x6d, 0x40, 0x9c, 0x2d, 0x1d, 0xfa, 0x32, 0x05, 0x84, 0x8a, 0x73, 0xc7, 0x8e,
	0x8c, 0x58, 0x9e, 0x71, 0x19, 0x61, 0x92, 0x97, 0xb2, 0x19, 0x2e, 0x3a, 0x87, 0x23, 0x6d, 0x2b,
	0x8d, 0x8f, 0x6a, 0xf2, 0x3b, 0xf7, 0xb6, 0xf3, 0x51, 0xbc, 0x2b, 0x1f, 0xa5, 0x3b, 0xf3, 0x51,
	0xd6, 0xde, 0xdd, 0x96, 0x8f, 0x8a, 0x94, 0x49, 0xe6, 0xe3, 0x19, 0x34, 0x37, 0xa0, 0x3e, 0x20,
	0x1b, 0x7f, 0x80, 0x13, 0x8b, 0x86, 0x5d, 0xe6, 0x4f, 0xdc, 0xe9, 0x32, 0xb0, 0x85, 0xcf, 0x51,
	0x52, 0xc4, 0x95, 0x55, 0xd5, 0xad, 0xd0, 0xef, 0x8f, 0xe3, 0x66, 0x9a, 0x66, 0xa3, 0xe7, 0x60,
	0x8e, 0xe9, 0xc4, 0x5e, 0x7a, 0x61, 0xd4, 0x91, 0xc5, 0xfc, 0xb9, 0x58, 0x87, 0x54, 0xcd, 0xe2,
	0x3c, 0xd9, 0xbb, 0x8f, 0x7f, 0x0d, 0xe6, 0xb6, 0x03, 0x3a, 0x80, 0x0b, 0x68, 0x38, 0xc9, 0x0d,
	0x69, 0xbf, 0x76, 0xfe, 0x56, 0xe6, 0xd6, 0xa5, 0x95, 0xd3, 0x2a, 0xf8, 0x6f, 0x06, 0x1c, 0xed,
	0x0c, 0xcf, 0x81, 0x13, 0xce, 0xc7, 0xbb, 0xb6, 0x4c, 0xe3, 0x2c, 0xdf, 0xaa, 0x9d, 0x7f, 0xf3,
	0x56, 0x33, 0x4a, 0xf4, 0x92, 0x05, 0x96, 0xf5, 0x82, 0xec, 0x3b, 0x09, 0x1d, 0x41, 0xd1, 0xa3,
	0x2b, 0xea, 0x49, 0x18, 0x8a, 0x44, 0x11, 0x22, 0x31, 0x33, 0x77, 0x3a, 0xa3, 0x3c, 0xbc, 0x92,
	0x9b, 0x79, 0xb9, 0x99, 0xe2, 0xe1, 0x7f, 0x19, 0x70, 0xba, 0xdf, 0xa2, 0x38, 0x98, 0xf3, 0x71,
	0x9c, 0x12, 0x45, 0xa0, 0x8f, 0xe0, 0x24, 0xfa, 0xa2, 0xf0, 0x57, 0xb6, 0xe7, 0x8e, 0xed, 0x90,
	0xea, 0xd9, 0x9e, 0x93, 0x23, 0x60, 0xdf, 0x36, 0xba, 0x84, 0xc7, 0x3e, 0x0b, 0xdd, 0x89, 0x4b,
	0xc7, 0x57, 0xcc, 0x91, 0x06, 0xb9, 0x1e, 0xcb, 0x66, 0x06, 0x87, 0x78, 0x9f, 0x6c, 0xab, 0xa0,
	0xa7, 0x50, 0x0c, 0xd9, 0x0d, 0xf5, 0xe5, 0xb5, 0xa9, 0x9d, 0x9f, 0xec, 0xd1, 0x25, 0x4a, 0x0a,
	0xff, 0x12, 0x9e, 0x7c, 0x79, 0xa9, 0xff, 0x6b, 0x0e, 0x1a, 0x29, 0x81, 0x07, 0x94, 0xf4, 0x3b,
	0xd0, 0xe0, 0x6b, 0xee, 0xb1, 0x69, 0xcf, 0xb7, 0xdf, 0x78, 0x74, 0xac, 0xf1, 0x4b, 0x33, 0xd5,
	0xa8, 0x16, 0x8c, 0x4b, 0xcf, 0x9e, 0x72, 0xdd, 0x58, 0x92, 0xac, 0x5b, 0xaf, 0x46, 0xe1, 0xf6,
	0xab, 0x81, 0x9e, 0xc6, 0x1f, 0xb4, 0x6a, 0xda, 0x3c, 0xc9, 0x04, 0x9f, 0xf9, 0x8e, 0x7d, 0x0e,
	0xd5, 0xb8, 0xef, 0x98, 0x25, 0x59, 0xc2, 0x59, 0xb8, 0xe2, 0xce, 0xd8, 0xf7, 0x27, 0x8c, 0x6c,
	0xc4, 0xf1, 0xa7, 0x50, 0x89, 0x52, 0x23, 0x82, 0x8a, 0x37, 0x62, 0x80, 0x92, 0x2c, 0xd1, 0x8c,
	0xde, 0x68, 0x6f, 0xfb, 0x51, 0xeb, 0x4d, 0x70, 0xe4, 0x5b, 0x21, 0x39, 0x5c, 0x34, 0x85, 0x10,
	0x14, 0xb8, 0xf8, 0x52, 0x55, 0x81, 0xcb, 0x35, 0xfe, 0x18, 0xaa, 0x9b, 0xea, 0xf9, 0x10, 0x2a,
	0x9e, 0x26, 0xf4, 0x25, 0xdc, 0x5b, 0x40, 0xb1, 0x20, 0xfe, 0xac, 0x04, 0x8d, 0x54, 0x60, 0xc2,
	0xce, 0x72, 0x33, 0x1d, 0xe5, 0x5a, 0xf0, 0x16, 0x76, 0x38, 0xd3, 0xde, 0xca, 0x35, 0xea, 0x40,
	0x51, 0x60, 0xa7, 0x26, 0xc2, 0xc1, 0xf9, 0xb7, 0x6e, 0x43, 0x6b, 0x43, 0x09, 0xd8, 0x29, 0x51,
	0x9a, 0xf7, 0x7a, 0x12, 0x88, 0x4f, 0xb1, 0x38, 0xe9, 0x45, 0x19, 0xfb, 0x86, 0x21, 0x26, 0x80,
	0xbd, 0xb2, 0x5d, 0x4f, 0x54, 0x94, 0x12, 0x29, 0xa9, 0x89, 0x9c, 0xe6, 0xa2, 0x01, 0xd4, 0x63,
	0x88, 0xfd, 0x09, 0x33, 0xcb, 0x3b, 0x9b, 0x54, 0xda, 0xe7, 0x8b, 0x84, 0x02, 0x49, 0xa9, 0x0b,
	0xc7, 0x39, 0x0d, 0x5c, 0xdb, 0x1b, 0x2e, 0xe7, 0x6f, 0x68, 0xa0, 0x47, 0x4a, 0x8a, 0x27, 0xf3,
	0xe5, 0xb1, 0xd0, 0xac, 0x2a, 0xcc, 0xc4, 0x5a, 0xe4, 0x76, 0x4c, 0x57, 0xae, 0x43, 0x4d, 0x50,
	0xef, 0x40, 0x45, 0x89, 0x86, 0xe4, 0x72, 0xcb, 0x7a, 0x61, 0xd6, 0xe4, 0x45, 0x51, 0x04, 0x7a,
	0x06, 0x55, 0x2f, 0x6e, 0x27, 0xf5, 0x3b, 0xda, 0xc9, 0x46, 0xf4, 0xf4, 0x1f, 0x06, 0xd4, 0x93,
	0xce, 0xa3, 0x03, 0xc8, 0xc5, 0x09, 0xcd, 0xa9, 0x74, 0xca, 0x52, 0xca, 0x6d, 0x4a, 0x09, 0x0d,
	0xd2, 0xe9, 0xfc, 0xee, 0xbd, 0xa1, 0x89, 0x89, 0x87, 0xa6, 0x16, 0xbf, 0x0b, 0x8d, 0x94, 0x2e,
	0x02, 0x28, 0x8d, 0x86, 0x57, 0xfd, 0x61, 0x2f, 0xfd, 0x76, 0xfb, 0x0d, 0x1c, 0xa4, 0xeb, 0x47,
	0xbc, 0xf2, 0xae, 0x87, 0x3f, 0x1f, 0x8e, 0x5e, 0x0f, 0x9b, 0x8f, 0x12, 0x5a, 0x86, 0xd8, 0x18,
	0x5d, 0x5e, 0x4a, 0x22, 0xb7, 0x39, 0x22, 0x2f, 0xf8, 0xa4, 0x37, 0x18, 0x7d, 0xd2, 0x7b, 0xd1,
	0x2c, 0xa0, 0x43, 0xa8, 0x0d, 0x3a, 0xfd, 0xe1, 0xab, 0xde, 0xb0, 0x33, 0xec, 0xf6, 0x9a, 0x45,
	0x7c, 0x08, 0x0d, 0xdd, 0x0e, 0x54, 0x83, 0xc7, 0x7f, 0x36, 0xe0, 0x20, 0xe2, 0x24, 0x5e, 0x47,
	0xf7, 0xeb, 0x7e, 0x4f, 0x53, 0x4f, 0xe9, 0x3b, 0x3b, 0xcf, 0x29, 0x54, 0x9c, 0x99, 0xed, 0x4f,
	0x69, 0x7f, 0xac, 0x6f, 0x7c, 0x4c, 0xe3, 0x7f, 0x1a, 0xf1, 0xc3, 0xf6, 0xde, 0xaf, 0x33, 0x01,
	0xbd, 0x1e, 0x54, 0x5d, 0xb6, 0xf4, 0x43, 0x9d, 0xe5, 0x14, 0x0f, 0xbd, 0x0f, 0x8f, 0x35, 0xdd,
	0x13, 0x19, 0x51, 0x82, 0xca, 0xfa, 0xf6, 0x86, 0xb8, 0x65, 0x71, 0x07, 0x53, 0xa2, 0xaa, 0x09,
	0x65, 0xb8, 0x29, 0x39, 0xa9, 0xae, 0x2f, 0x6c, 0x86, 0x8b, 0x1b, 0x50, 0x4b, 0xfc, 0xb9, 0xc0,
	0x9f, 0xe7, 0xa1, 0xdc, 0x1f, 0x89, 0x38, 0x39, 0x7a, 0x06, 0xc7, 0xf6, 0x8a, 0x0a, 0xb4, 0x12,
	0xcf, 0x98, 0x38, 0xda, 0x02, 0xd9, 0xb3, 0x2b, 0x86, 0xb7, 0xde, 0x49, 0x3e, 0x4c, 0xe3, 0xa7,
	0x52, 0x81, 0xec, 0xdb, 0x16, 0x43, 0x86, 0xf2, 0xd0, 0x9d, 0x8b, 0x71, 0x9e, 0xb5, 0x99, 0x97,
	0xaa, 0x7b, 0xf7, 0xd1, 0x0f, 0xe0, 0xeb, 0xf1, 0xde, 0x96, 0xdd, 0x82, 0x54, 0xde, 0x2f, 0x20,
	0xe0, 0x0a, 0xa8, 0x3d, 0x1e, 0x2d, 0x68, 0xa0, 0x2f, 0x79, 0x51, 0xaa, 0x64, 0xb8, 0x22, 0xf5,
	0xbf, 0x13, 0xba, 0x09, 0x41, 0xf5, 0xb7, 0x28, 0xcb, 0x16, 0x92, 0x09, 0x7c, 0xa4, 0x17, 0x65,
	0x25, 0x99, 0x61, 0x8b, 0x47, 0x43, 0x12, 0x10, 0x29, 0x5a, 0x91, 0xa2, 0x5b, 0x7c, 0x4c, 0x32,
	0xf7, 0x8f, 0xef, 0x9c, 0x11, 0xef, 0xab, 0x06, 0x12, 0x55, 0xfd, 0x71, 0xa6, 0xea, 0x75, 0x82,
	0x55, 0x7f, 0xe0, 0xf8, 0x1a, 0xea, 0xaa, 0x04, 0xf4, 0xf5, 0xea, 0x25, 0x4a, 0x47, 0x0a, 0xea,
	0x11, 0xf6, 0x8d, 0x7d, 0x7d, 0x48, 0x9d, 0x96, 0x51, 0xc2, 0xff, 0x31, 0xa0, 0xd8, 0x5b, 0x51,
	0x5f, 0xfe, 0xee, 0xa3, 0x62, 0xa1, 0xef, 0x69, 0x9e, 0x44, 0xa4, 0x6c, 0x4d, 0x62, 0x19, 0xb5,
	0x26, 0x7d, 0x3f, 0x92, 0x3c, 0x71, 0x29, 0xc5, 0xf7, 0x5d, 0x5c, 0x04, 0x55, 0x12, 0xd3, 0xe8,
	0x7b, 0x50, 0xe1, 0x74, 0x45, 0x03, 0x37, 0x5c, 0xcb, 0x1c, 0x1f, 0x6c, 0x39, 0x29, 0x3d, 0x68,
	0x5b, 0x5a, 0x88, 0xc4, 0xe2, 0xf8, 0x17, 0x50, 0x89, 0xb8, 0xe8, 0x31, 0x34, 0xfa, 0xc3, 0xcb,
	0x11, 0x19, 0x74, 0x5e, 0xf5, 0x47, 0xc3, 0xce, 0x95, 0xea, 0x79, 0xdd, 0xab, 0x5e, 0x87, 0xa8,
	0x46, 0xf6, 0xba, 0x43, 0x86, 0xfd, 0xe1, 0x4f, 0x54, 0x23, 0x1b, 0xf4, 0x87, 0xb2, 0x91, 0x89,
	0x65, 0xe7, 0x67, 0x23, 0xd2, 0x2c, 0xa0, 0x3a, 0x54, 0xba, 0xa4, 0xff, 0xaa, 0xdf, 0xed, 0x5c,
	0x35, 0x8b, 0x78, 0x0c, 0x75, 0x69, 0xf6, 0xe1, 0x0f, 0x90, 0xf7, 0xa0, 0x28, 0x63, 0xd7, 0x89,
	0x3b, 0xda, 0x15, 0x0c, 0x51, 0x22, 0xf8, 0x03, 0xf9, 0xc9, 0xe9, 0x53, 0x47, 0x40, 0xfe, 0x92,
	0x31, 0x2f, 0x32, 0x77, 0x0c, 0xa5, 0x05, 0x63, 0x5e, 0x6c, 0x45, 0x53, 0xd8, 0x84, 0xe3, 0xac,
	0x82, 0xca, 0x38, 0xfe, 0x00, 0x8a, 0x3d, 0x3f, 0x0c, 0xd6, 0xa8, 0x09, 0xf9, 0x1b, 0xba, 0xd6,
	0x7a, 0x62, 0x29, 0xc6, 0xe1, 0xca, 0xf6, 0x96, 0xd1, 0x03, 0x5c, 0x11, 0xf8, 0x1a, 0x6a, 0x83,
	0xe9, 0x3c, 0x0e, 0xb0, 0x09, 0x79, 0x67, 0x1e, 0x99, 0x13, 0x4b, 0xf4, 0x1d, 0x80, 0x85, 0x1d,
	0xd8, 0x73, 0x1a, 0xd2, 0x40, 0x94, 0x61, 0x7e, 0x57, 0x34, 0xc2, 0x24, 0x49, 0xc8, 0xe1, 0x1f,
	0x41, 0x5d, 0x1d, 0xab, 0x2b, 0xb1, 0x0d, 0xe5, 0x80, 0xf2, 0xa5, 0x17, 0x97, 0xe0, 0xee, 0x23,
	0x22, 0xa1, 0xf3, 0xcf, 0x0c, 0xc8, 0x59, 0x1c, 0xfd, 0x50, 0xfd, 0x6f, 0x45, 0xc7, 0xbb, 0xff,
	0x6a, 0x9c, 0x9e, 0xec, 0xf9, 0xa1, 0x8a, 0x1f, 0xb5, 0x8c, 0x6f, 0x1b, 0x42, 0x5d, 0xdc, 0xcd,
	0xff, 0x51, 0xfd, 0xe2, 0xfb, 0x80, 0x1d, 0x36, 0x6f, 0xd3, 0xb9, 0x13, 0xc9, 0x31, 0xde, 0x16,
	0x6f, 0x55, 0xf5, 0x5f, 0xdc, 0x61, 0x5e, 0x9b, 0xf3, 0x8b, 0x27, 0x56, 0x32, 0xf5, 0xba, 0xd6,
	0xf9, 0x9b, 0x92, 0x94, 0xf9, 0xf0, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x18, 0x50, 0x33, 0x09,
	0x4c, 0x17, 0x00, 0x00,
}
