// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocolbuffer/storage.proto

package protocolbuffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_SUCCESS Response_Status = 1
	Response_ERROR   Response_Status = 2
)

var Response_Status_name = map[int32]string{
	1: "SUCCESS",
	2: "ERROR",
}
var Response_Status_value = map[string]int32{
	"SUCCESS": 1,
	"ERROR":   2,
}

func (x Response_Status) Enum() *Response_Status {
	p := new(Response_Status)
	*p = x
	return p
}
func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (x *Response_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_Status_value, data, "Response_Status")
	if err != nil {
		return err
	}
	*x = Response_Status(value)
	return nil
}
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{1, 0}
}

type PartitionInfo_PartitionState int32

const (
	PartitionInfo_UNKNOWN     PartitionInfo_PartitionState = 0
	PartitionInfo_ONLINE      PartitionInfo_PartitionState = 1
	PartitionInfo_OFFLINE     PartitionInfo_PartitionState = 2
	PartitionInfo_ERROR       PartitionInfo_PartitionState = 3
	PartitionInfo_REMOVED     PartitionInfo_PartitionState = 4
	PartitionInfo_MAINTENANCE PartitionInfo_PartitionState = 5
)

var PartitionInfo_PartitionState_name = map[int32]string{
	0: "UNKNOWN",
	1: "ONLINE",
	2: "OFFLINE",
	3: "ERROR",
	4: "REMOVED",
	5: "MAINTENANCE",
}
var PartitionInfo_PartitionState_value = map[string]int32{
	"UNKNOWN":     0,
	"ONLINE":      1,
	"OFFLINE":     2,
	"ERROR":       3,
	"REMOVED":     4,
	"MAINTENANCE": 5,
}

func (x PartitionInfo_PartitionState) Enum() *PartitionInfo_PartitionState {
	p := new(PartitionInfo_PartitionState)
	*p = x
	return p
}
func (x PartitionInfo_PartitionState) String() string {
	return proto.EnumName(PartitionInfo_PartitionState_name, int32(x))
}
func (x *PartitionInfo_PartitionState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PartitionInfo_PartitionState_value, data, "PartitionInfo_PartitionState")
	if err != nil {
		return err
	}
	*x = PartitionInfo_PartitionState(value)
	return nil
}
func (PartitionInfo_PartitionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{21, 0}
}

type PartitionInfo_BlockBinInfo_BlockBinState int32

const (
	PartitionInfo_BlockBinInfo_ONLINE PartitionInfo_BlockBinInfo_BlockBinState = 1
	PartitionInfo_BlockBinInfo_ERROR  PartitionInfo_BlockBinInfo_BlockBinState = 2
)

var PartitionInfo_BlockBinInfo_BlockBinState_name = map[int32]string{
	1: "ONLINE",
	2: "ERROR",
}
var PartitionInfo_BlockBinInfo_BlockBinState_value = map[string]int32{
	"ONLINE": 1,
	"ERROR":  2,
}

func (x PartitionInfo_BlockBinInfo_BlockBinState) Enum() *PartitionInfo_BlockBinInfo_BlockBinState {
	p := new(PartitionInfo_BlockBinInfo_BlockBinState)
	*p = x
	return p
}
func (x PartitionInfo_BlockBinInfo_BlockBinState) String() string {
	return proto.EnumName(PartitionInfo_BlockBinInfo_BlockBinState_name, int32(x))
}
func (x *PartitionInfo_BlockBinInfo_BlockBinState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PartitionInfo_BlockBinInfo_BlockBinState_value, data, "PartitionInfo_BlockBinInfo_BlockBinState")
	if err != nil {
		return err
	}
	*x = PartitionInfo_BlockBinInfo_BlockBinState(value)
	return nil
}
func (PartitionInfo_BlockBinInfo_BlockBinState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{21, 0, 0}
}

type Event_Severity int32

const (
	Event_INFORMATIONAL Event_Severity = 1
	Event_CLEAR         Event_Severity = 2
	Event_WARNING       Event_Severity = 3
	Event_MINOR         Event_Severity = 4
	Event_MAJOR         Event_Severity = 5
	Event_CRITICAL      Event_Severity = 6
)

var Event_Severity_name = map[int32]string{
	1: "INFORMATIONAL",
	2: "CLEAR",
	3: "WARNING",
	4: "MINOR",
	5: "MAJOR",
	6: "CRITICAL",
}
var Event_Severity_value = map[string]int32{
	"INFORMATIONAL": 1,
	"CLEAR":         2,
	"WARNING":       3,
	"MINOR":         4,
	"MAJOR":         5,
	"CRITICAL":      6,
}

func (x Event_Severity) Enum() *Event_Severity {
	p := new(Event_Severity)
	*p = x
	return p
}
func (x Event_Severity) String() string {
	return proto.EnumName(Event_Severity_name, int32(x))
}
func (x *Event_Severity) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Event_Severity_value, data, "Event_Severity")
	if err != nil {
		return err
	}
	*x = Event_Severity(value)
	return nil
}
func (Event_Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{29, 0}
}

type Request struct {
	Version                      *int64   `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	MessageCheckSum              []byte   `protobuf:"bytes,2,req,name=messageCheckSum" json:"messageCheckSum,omitempty"`
	Context                      []byte   `protobuf:"bytes,3,opt,name=context" json:"context,omitempty"`
	RequestId                    *string  `protobuf:"bytes,4,opt,name=requestId" json:"requestId,omitempty"`
	Origin                       *string  `protobuf:"bytes,5,opt,name=origin" json:"origin,omitempty"`
	Timeout                      *uint64  `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{0}
}

var extRange_Request = []proto.ExtensionRange{
	{Start: 1000, End: 536870911},
}

func (*Request) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Request
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Request) GetMessageCheckSum() []byte {
	if m != nil {
		return m.MessageCheckSum
	}
	return nil
}

func (m *Request) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Request) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *Request) GetOrigin() string {
	if m != nil && m.Origin != nil {
		return *m.Origin
	}
	return ""
}

func (m *Request) GetTimeout() uint64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

//
// Base response message
// All responses are wrapped inside of this message
//
type Response struct {
	// used for dealing with changes in protocol messages
	Version *int64 `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	// Used generically for success/failure of request. Additional information
	// may be provided by the errorMessage field and child response message may have additional
	// states/messages
	Status          *Response_Status `protobuf:"varint,2,req,name=status,enum=storageserver.Response_Status" json:"status,omitempty"`
	MessageCheckSum []byte           `protobuf:"bytes,3,req,name=messageCheckSum" json:"messageCheckSum,omitempty"`
	// Used generically
	ErrorMessage *string `protobuf:"bytes,4,opt,name=errorMessage" json:"errorMessage,omitempty"`
	// If included will be returned in the response
	Context                      []byte   `protobuf:"bytes,5,opt,name=context" json:"context,omitempty"`
	RequestId                    *string  `protobuf:"bytes,6,opt,name=requestId" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{1}
}

var extRange_Response = []proto.ExtensionRange{
	{Start: 1000, End: 536870911},
}

func (*Response) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Response
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Response) GetStatus() Response_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Response_SUCCESS
}

func (m *Response) GetMessageCheckSum() []byte {
	if m != nil {
		return m.MessageCheckSum
	}
	return nil
}

func (m *Response) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

func (m *Response) GetContext() []byte {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Response) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

type RequestMetadata struct {
	ChunkSize            *uint32  `protobuf:"varint,1,opt,name=chunkSize" json:"chunkSize,omitempty"`
	ChunkOffset          *uint64  `protobuf:"varint,2,opt,name=chunkOffset" json:"chunkOffset,omitempty"`
	ShouldCache          *bool    `protobuf:"varint,3,opt,name=shouldCache" json:"shouldCache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMetadata) Reset()         { *m = RequestMetadata{} }
func (m *RequestMetadata) String() string { return proto.CompactTextString(m) }
func (*RequestMetadata) ProtoMessage()    {}
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{2}
}
func (m *RequestMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMetadata.Unmarshal(m, b)
}
func (m *RequestMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMetadata.Marshal(b, m, deterministic)
}
func (dst *RequestMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMetadata.Merge(dst, src)
}
func (m *RequestMetadata) XXX_Size() int {
	return xxx_messageInfo_RequestMetadata.Size(m)
}
func (m *RequestMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMetadata proto.InternalMessageInfo

func (m *RequestMetadata) GetChunkSize() uint32 {
	if m != nil && m.ChunkSize != nil {
		return *m.ChunkSize
	}
	return 0
}

func (m *RequestMetadata) GetChunkOffset() uint64 {
	if m != nil && m.ChunkOffset != nil {
		return *m.ChunkOffset
	}
	return 0
}

func (m *RequestMetadata) GetShouldCache() bool {
	if m != nil && m.ShouldCache != nil {
		return *m.ShouldCache
	}
	return false
}

//
// Calls datasync on the specified file
// Used when WriteRequest sets syncOnWrite = false as a final step
// to ensure data was written fully to disk
type SyncBlockBinRequest struct {
	PartitionUuid        *string          `protobuf:"bytes,1,req,name=partitionUuid" json:"partitionUuid,omitempty"`
	FileName             *string          `protobuf:"bytes,2,req,name=fileName" json:"fileName,omitempty"`
	Metadata             *RequestMetadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SyncBlockBinRequest) Reset()         { *m = SyncBlockBinRequest{} }
func (m *SyncBlockBinRequest) String() string { return proto.CompactTextString(m) }
func (*SyncBlockBinRequest) ProtoMessage()    {}
func (*SyncBlockBinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{3}
}
func (m *SyncBlockBinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncBlockBinRequest.Unmarshal(m, b)
}
func (m *SyncBlockBinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncBlockBinRequest.Marshal(b, m, deterministic)
}
func (dst *SyncBlockBinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncBlockBinRequest.Merge(dst, src)
}
func (m *SyncBlockBinRequest) XXX_Size() int {
	return xxx_messageInfo_SyncBlockBinRequest.Size(m)
}
func (m *SyncBlockBinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncBlockBinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncBlockBinRequest proto.InternalMessageInfo

func (m *SyncBlockBinRequest) GetPartitionUuid() string {
	if m != nil && m.PartitionUuid != nil {
		return *m.PartitionUuid
	}
	return ""
}

func (m *SyncBlockBinRequest) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *SyncBlockBinRequest) GetMetadata() *RequestMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// used to help identify response of SyncBlockBinRequest
type SyncBlockBinResponse struct {
	ServerStartTime      *string  `protobuf:"bytes,1,req,name=serverStartTime" json:"serverStartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncBlockBinResponse) Reset()         { *m = SyncBlockBinResponse{} }
func (m *SyncBlockBinResponse) String() string { return proto.CompactTextString(m) }
func (*SyncBlockBinResponse) ProtoMessage()    {}
func (*SyncBlockBinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{4}
}
func (m *SyncBlockBinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncBlockBinResponse.Unmarshal(m, b)
}
func (m *SyncBlockBinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncBlockBinResponse.Marshal(b, m, deterministic)
}
func (dst *SyncBlockBinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncBlockBinResponse.Merge(dst, src)
}
func (m *SyncBlockBinResponse) XXX_Size() int {
	return xxx_messageInfo_SyncBlockBinResponse.Size(m)
}
func (m *SyncBlockBinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncBlockBinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncBlockBinResponse proto.InternalMessageInfo

func (m *SyncBlockBinResponse) GetServerStartTime() string {
	if m != nil && m.ServerStartTime != nil {
		return *m.ServerStartTime
	}
	return ""
}

//
// Writes a block of data to the specified location
type WriteRequest struct {
	PartitionUuid  *string `protobuf:"bytes,1,req,name=partitionUuid" json:"partitionUuid,omitempty"`
	FileName       *string `protobuf:"bytes,2,req,name=fileName" json:"fileName,omitempty"`
	StartingOffset *int64  `protobuf:"varint,3,req,name=startingOffset" json:"startingOffset,omitempty"`
	DataLength     *int64  `protobuf:"varint,4,req,name=dataLength" json:"dataLength,omitempty"`
	SyncOnWrite    *bool   `protobuf:"varint,5,opt,name=syncOnWrite,def=1" json:"syncOnWrite,omitempty"`
	// if present will compare against checksum calculated by server
	// if checksums do not match an error will be returned
	// calculated checksum in response will always be returned regardless
	DataCheckSum []byte `protobuf:"bytes,6,opt,name=dataCheckSum" json:"dataCheckSum,omitempty"`
	// if present and true, storage server will not write data to the disk
	// this flag is only used for testing storage server
	SkipWrite            *bool            `protobuf:"varint,7,opt,name=skipWrite,def=0" json:"skipWrite,omitempty"`
	Metadata             *RequestMetadata `protobuf:"bytes,8,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{5}
}
func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (dst *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(dst, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

const Default_WriteRequest_SyncOnWrite bool = true
const Default_WriteRequest_SkipWrite bool = false

func (m *WriteRequest) GetPartitionUuid() string {
	if m != nil && m.PartitionUuid != nil {
		return *m.PartitionUuid
	}
	return ""
}

func (m *WriteRequest) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *WriteRequest) GetStartingOffset() int64 {
	if m != nil && m.StartingOffset != nil {
		return *m.StartingOffset
	}
	return 0
}

func (m *WriteRequest) GetDataLength() int64 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

func (m *WriteRequest) GetSyncOnWrite() bool {
	if m != nil && m.SyncOnWrite != nil {
		return *m.SyncOnWrite
	}
	return Default_WriteRequest_SyncOnWrite
}

func (m *WriteRequest) GetDataCheckSum() []byte {
	if m != nil {
		return m.DataCheckSum
	}
	return nil
}

func (m *WriteRequest) GetSkipWrite() bool {
	if m != nil && m.SkipWrite != nil {
		return *m.SkipWrite
	}
	return Default_WriteRequest_SkipWrite
}

func (m *WriteRequest) GetMetadata() *RequestMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type WriteResponse struct {
	// Hash of the data written so the client can
	// verify if the data was correct or not and take
	// the appropriate action.
	DataCheckSum []byte `protobuf:"bytes,1,opt,name=dataCheckSum" json:"dataCheckSum,omitempty"`
	// if syncOnWrite = false, returns start time of
	// server to know if a reset happened between the call
	// to write and the call to sync to disk
	ServerStartTime      *string  `protobuf:"bytes,2,opt,name=serverStartTime" json:"serverStartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{6}
}
func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (dst *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(dst, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetDataCheckSum() []byte {
	if m != nil {
		return m.DataCheckSum
	}
	return nil
}

func (m *WriteResponse) GetServerStartTime() string {
	if m != nil && m.ServerStartTime != nil {
		return *m.ServerStartTime
	}
	return ""
}

//
// Read the requested block
type ReadRequest struct {
	PartitionUuid        *string          `protobuf:"bytes,1,req,name=partitionUuid" json:"partitionUuid,omitempty"`
	FileName             *string          `protobuf:"bytes,2,req,name=fileName" json:"fileName,omitempty"`
	StartingOffset       *int64           `protobuf:"varint,3,req,name=startingOffset" json:"startingOffset,omitempty"`
	DataLength           *int64           `protobuf:"varint,4,req,name=dataLength" json:"dataLength,omitempty"`
	Metadata             *RequestMetadata `protobuf:"bytes,5,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{7}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (dst *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(dst, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetPartitionUuid() string {
	if m != nil && m.PartitionUuid != nil {
		return *m.PartitionUuid
	}
	return ""
}

func (m *ReadRequest) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *ReadRequest) GetStartingOffset() int64 {
	if m != nil && m.StartingOffset != nil {
		return *m.StartingOffset
	}
	return 0
}

func (m *ReadRequest) GetDataLength() int64 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

func (m *ReadRequest) GetMetadata() *RequestMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ReadResponse struct {
	DataLength           *int64   `protobuf:"varint,1,req,name=dataLength" json:"dataLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{8}
}
func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (dst *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(dst, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetDataLength() int64 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

// calculates a checksum based on the data provided and
// returns it in the response
type VerifyDataRequest struct {
	PartitionUuid        *string  `protobuf:"bytes,1,req,name=partitionUuid" json:"partitionUuid,omitempty"`
	FileName             *string  `protobuf:"bytes,2,req,name=fileName" json:"fileName,omitempty"`
	StartingOffset       *int64   `protobuf:"varint,3,req,name=startingOffset" json:"startingOffset,omitempty"`
	DataLength           *int64   `protobuf:"varint,4,req,name=dataLength" json:"dataLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyDataRequest) Reset()         { *m = VerifyDataRequest{} }
func (m *VerifyDataRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyDataRequest) ProtoMessage()    {}
func (*VerifyDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{9}
}
func (m *VerifyDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyDataRequest.Unmarshal(m, b)
}
func (m *VerifyDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyDataRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyDataRequest.Merge(dst, src)
}
func (m *VerifyDataRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyDataRequest.Size(m)
}
func (m *VerifyDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyDataRequest proto.InternalMessageInfo

func (m *VerifyDataRequest) GetPartitionUuid() string {
	if m != nil && m.PartitionUuid != nil {
		return *m.PartitionUuid
	}
	return ""
}

func (m *VerifyDataRequest) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *VerifyDataRequest) GetStartingOffset() int64 {
	if m != nil && m.StartingOffset != nil {
		return *m.StartingOffset
	}
	return 0
}

func (m *VerifyDataRequest) GetDataLength() int64 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

type VerifyDataResponse struct {
	DataCheckSum         []byte   `protobuf:"bytes,1,req,name=dataCheckSum" json:"dataCheckSum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyDataResponse) Reset()         { *m = VerifyDataResponse{} }
func (m *VerifyDataResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyDataResponse) ProtoMessage()    {}
func (*VerifyDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{10}
}
func (m *VerifyDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyDataResponse.Unmarshal(m, b)
}
func (m *VerifyDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyDataResponse.Marshal(b, m, deterministic)
}
func (dst *VerifyDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyDataResponse.Merge(dst, src)
}
func (m *VerifyDataResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyDataResponse.Size(m)
}
func (m *VerifyDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyDataResponse proto.InternalMessageInfo

func (m *VerifyDataResponse) GetDataCheckSum() []byte {
	if m != nil {
		return m.DataCheckSum
	}
	return nil
}

// pull request from another storage server
type CopyFromRequest struct {
	// server to connect to - host:port
	SourceServerName     *string  `protobuf:"bytes,1,req,name=sourceServerName" json:"sourceServerName,omitempty"`
	SoucePartitionUuid   *string  `protobuf:"bytes,2,req,name=soucePartitionUuid" json:"soucePartitionUuid,omitempty"`
	SourceFileName       *string  `protobuf:"bytes,3,req,name=sourceFileName" json:"sourceFileName,omitempty"`
	SourceStartingOffset *string  `protobuf:"bytes,4,req,name=sourceStartingOffset" json:"sourceStartingOffset,omitempty"`
	PartitionUuid        *string  `protobuf:"bytes,5,req,name=partitionUuid" json:"partitionUuid,omitempty"`
	FileName             *string  `protobuf:"bytes,6,req,name=fileName" json:"fileName,omitempty"`
	StartingOffset       *string  `protobuf:"bytes,7,req,name=startingOffset" json:"startingOffset,omitempty"`
	DataLength           *string  `protobuf:"bytes,8,req,name=dataLength" json:"dataLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromRequest) Reset()         { *m = CopyFromRequest{} }
func (m *CopyFromRequest) String() string { return proto.CompactTextString(m) }
func (*CopyFromRequest) ProtoMessage()    {}
func (*CopyFromRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{11}
}
func (m *CopyFromRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromRequest.Unmarshal(m, b)
}
func (m *CopyFromRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromRequest.Marshal(b, m, deterministic)
}
func (dst *CopyFromRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromRequest.Merge(dst, src)
}
func (m *CopyFromRequest) XXX_Size() int {
	return xxx_messageInfo_CopyFromRequest.Size(m)
}
func (m *CopyFromRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromRequest proto.InternalMessageInfo

func (m *CopyFromRequest) GetSourceServerName() string {
	if m != nil && m.SourceServerName != nil {
		return *m.SourceServerName
	}
	return ""
}

func (m *CopyFromRequest) GetSoucePartitionUuid() string {
	if m != nil && m.SoucePartitionUuid != nil {
		return *m.SoucePartitionUuid
	}
	return ""
}

func (m *CopyFromRequest) GetSourceFileName() string {
	if m != nil && m.SourceFileName != nil {
		return *m.SourceFileName
	}
	return ""
}

func (m *CopyFromRequest) GetSourceStartingOffset() string {
	if m != nil && m.SourceStartingOffset != nil {
		return *m.SourceStartingOffset
	}
	return ""
}

func (m *CopyFromRequest) GetPartitionUuid() string {
	if m != nil && m.PartitionUuid != nil {
		return *m.PartitionUuid
	}
	return ""
}

func (m *CopyFromRequest) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *CopyFromRequest) GetStartingOffset() string {
	if m != nil && m.StartingOffset != nil {
		return *m.StartingOffset
	}
	return ""
}

func (m *CopyFromRequest) GetDataLength() string {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return ""
}

type CopyFromResponse struct {
	DataCheckSum         []byte   `protobuf:"bytes,1,opt,name=dataCheckSum" json:"dataCheckSum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyFromResponse) Reset()         { *m = CopyFromResponse{} }
func (m *CopyFromResponse) String() string { return proto.CompactTextString(m) }
func (*CopyFromResponse) ProtoMessage()    {}
func (*CopyFromResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{12}
}
func (m *CopyFromResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyFromResponse.Unmarshal(m, b)
}
func (m *CopyFromResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyFromResponse.Marshal(b, m, deterministic)
}
func (dst *CopyFromResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyFromResponse.Merge(dst, src)
}
func (m *CopyFromResponse) XXX_Size() int {
	return xxx_messageInfo_CopyFromResponse.Size(m)
}
func (m *CopyFromResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyFromResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyFromResponse proto.InternalMessageInfo

func (m *CopyFromResponse) GetDataCheckSum() []byte {
	if m != nil {
		return m.DataCheckSum
	}
	return nil
}

type SetConfigurationRequest struct {
	// change id
	StorageServerId *string `protobuf:"bytes,1,opt,name=storageServerId" json:"storageServerId,omitempty"`
	// change default blockbin byte size
	DefaultBlockBinSizeBytes *int64   `protobuf:"varint,2,opt,name=defaultBlockBinSizeBytes" json:"defaultBlockBinSizeBytes,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *SetConfigurationRequest) Reset()         { *m = SetConfigurationRequest{} }
func (m *SetConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigurationRequest) ProtoMessage()    {}
func (*SetConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{13}
}
func (m *SetConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigurationRequest.Unmarshal(m, b)
}
func (m *SetConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigurationRequest.Marshal(b, m, deterministic)
}
func (dst *SetConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigurationRequest.Merge(dst, src)
}
func (m *SetConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigurationRequest.Size(m)
}
func (m *SetConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigurationRequest proto.InternalMessageInfo

func (m *SetConfigurationRequest) GetStorageServerId() string {
	if m != nil && m.StorageServerId != nil {
		return *m.StorageServerId
	}
	return ""
}

func (m *SetConfigurationRequest) GetDefaultBlockBinSizeBytes() int64 {
	if m != nil && m.DefaultBlockBinSizeBytes != nil {
		return *m.DefaultBlockBinSizeBytes
	}
	return 0
}

type SetConfigurationResponse struct {
	Configuration        *Configuration `protobuf:"bytes,1,req,name=configuration" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetConfigurationResponse) Reset()         { *m = SetConfigurationResponse{} }
func (m *SetConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigurationResponse) ProtoMessage()    {}
func (*SetConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{14}
}
func (m *SetConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigurationResponse.Unmarshal(m, b)
}
func (m *SetConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigurationResponse.Marshal(b, m, deterministic)
}
func (dst *SetConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigurationResponse.Merge(dst, src)
}
func (m *SetConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigurationResponse.Size(m)
}
func (m *SetConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigurationResponse proto.InternalMessageInfo

func (m *SetConfigurationResponse) GetConfiguration() *Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type ConfigurationRequest struct {
	SsdConfigurationRequest []*ConfigurationRequestForSSD `protobuf:"bytes,1,rep,name=ssdConfigurationRequest" json:"ssdConfigurationRequest,omitempty"`
	Level                   *int32                        `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	HighestLevel            *int32                        `protobuf:"varint,3,opt,name=highestLevel" json:"highestLevel,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                      `json:"-"`
	XXX_unrecognized        []byte                        `json:"-"`
	XXX_sizecache           int32                         `json:"-"`
}

func (m *ConfigurationRequest) Reset()         { *m = ConfigurationRequest{} }
func (m *ConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigurationRequest) ProtoMessage()    {}
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{15}
}
func (m *ConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationRequest.Unmarshal(m, b)
}
func (m *ConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationRequest.Marshal(b, m, deterministic)
}
func (dst *ConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationRequest.Merge(dst, src)
}
func (m *ConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigurationRequest.Size(m)
}
func (m *ConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationRequest proto.InternalMessageInfo

func (m *ConfigurationRequest) GetSsdConfigurationRequest() []*ConfigurationRequestForSSD {
	if m != nil {
		return m.SsdConfigurationRequest
	}
	return nil
}

func (m *ConfigurationRequest) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *ConfigurationRequest) GetHighestLevel() int32 {
	if m != nil && m.HighestLevel != nil {
		return *m.HighestLevel
	}
	return 0
}

type ConfigurationRequestForSSD struct {
	SsdId                   *string    `protobuf:"bytes,1,req,name=ssdId" json:"ssdId,omitempty"`
	RequestInvalidatedCache *bool      `protobuf:"varint,2,req,name=requestInvalidatedCache" json:"requestInvalidatedCache,omitempty"`
	NotifiedLocations       *Locations `protobuf:"bytes,3,opt,name=notifiedLocations" json:"notifiedLocations,omitempty"`
	Token                   *Location  `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}   `json:"-"`
	XXX_unrecognized        []byte     `json:"-"`
	XXX_sizecache           int32      `json:"-"`
}

func (m *ConfigurationRequestForSSD) Reset()         { *m = ConfigurationRequestForSSD{} }
func (m *ConfigurationRequestForSSD) String() string { return proto.CompactTextString(m) }
func (*ConfigurationRequestForSSD) ProtoMessage()    {}
func (*ConfigurationRequestForSSD) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{16}
}
func (m *ConfigurationRequestForSSD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationRequestForSSD.Unmarshal(m, b)
}
func (m *ConfigurationRequestForSSD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationRequestForSSD.Marshal(b, m, deterministic)
}
func (dst *ConfigurationRequestForSSD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationRequestForSSD.Merge(dst, src)
}
func (m *ConfigurationRequestForSSD) XXX_Size() int {
	return xxx_messageInfo_ConfigurationRequestForSSD.Size(m)
}
func (m *ConfigurationRequestForSSD) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationRequestForSSD.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationRequestForSSD proto.InternalMessageInfo

func (m *ConfigurationRequestForSSD) GetSsdId() string {
	if m != nil && m.SsdId != nil {
		return *m.SsdId
	}
	return ""
}

func (m *ConfigurationRequestForSSD) GetRequestInvalidatedCache() bool {
	if m != nil && m.RequestInvalidatedCache != nil {
		return *m.RequestInvalidatedCache
	}
	return false
}

func (m *ConfigurationRequestForSSD) GetNotifiedLocations() *Locations {
	if m != nil {
		return m.NotifiedLocations
	}
	return nil
}

func (m *ConfigurationRequestForSSD) GetToken() *Location {
	if m != nil {
		return m.Token
	}
	return nil
}

type ConfigurationResponse struct {
	Configuration        *Configuration `protobuf:"bytes,1,req,name=configuration" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigurationResponse) Reset()         { *m = ConfigurationResponse{} }
func (m *ConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigurationResponse) ProtoMessage()    {}
func (*ConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{17}
}
func (m *ConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationResponse.Unmarshal(m, b)
}
func (m *ConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationResponse.Marshal(b, m, deterministic)
}
func (dst *ConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationResponse.Merge(dst, src)
}
func (m *ConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigurationResponse.Size(m)
}
func (m *ConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationResponse proto.InternalMessageInfo

func (m *ConfigurationResponse) GetConfiguration() *Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type Configuration struct {
	StorageServerId          *string          `protobuf:"bytes,1,req,name=storageServerId" json:"storageServerId,omitempty"`
	SyslogEnabled            *bool            `protobuf:"varint,2,req,name=syslogEnabled" json:"syslogEnabled,omitempty"`
	SyslogFlags              *string          `protobuf:"bytes,3,req,name=syslogFlags" json:"syslogFlags,omitempty"`
	DefaultBlockBinSizeBytes *int64           `protobuf:"varint,4,req,name=defaultBlockBinSizeBytes" json:"defaultBlockBinSizeBytes,omitempty"`
	Status                   *Status          `protobuf:"bytes,5,req,name=status" json:"status,omitempty"`
	Partition                []*PartitionInfo `protobuf:"bytes,6,rep,name=partition" json:"partition,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}         `json:"-"`
	XXX_unrecognized         []byte           `json:"-"`
	XXX_sizecache            int32            `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{18}
}
func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (dst *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(dst, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetStorageServerId() string {
	if m != nil && m.StorageServerId != nil {
		return *m.StorageServerId
	}
	return ""
}

func (m *Configuration) GetSyslogEnabled() bool {
	if m != nil && m.SyslogEnabled != nil {
		return *m.SyslogEnabled
	}
	return false
}

func (m *Configuration) GetSyslogFlags() string {
	if m != nil && m.SyslogFlags != nil {
		return *m.SyslogFlags
	}
	return ""
}

func (m *Configuration) GetDefaultBlockBinSizeBytes() int64 {
	if m != nil && m.DefaultBlockBinSizeBytes != nil {
		return *m.DefaultBlockBinSizeBytes
	}
	return 0
}

func (m *Configuration) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Configuration) GetPartition() []*PartitionInfo {
	if m != nil {
		return m.Partition
	}
	return nil
}

type Location struct {
	PartitionId          *string  `protobuf:"bytes,1,req,name=partitionId" json:"partitionId,omitempty"`
	BlockBinId           *string  `protobuf:"bytes,2,req,name=blockBinId" json:"blockBinId,omitempty"`
	Offset               *int64   `protobuf:"varint,3,req,name=offset" json:"offset,omitempty"`
	Size                 *int64   `protobuf:"varint,4,req,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{19}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetPartitionId() string {
	if m != nil && m.PartitionId != nil {
		return *m.PartitionId
	}
	return ""
}

func (m *Location) GetBlockBinId() string {
	if m != nil && m.BlockBinId != nil {
		return *m.BlockBinId
	}
	return ""
}

func (m *Location) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *Location) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type Locations struct {
	Location             []*Location `protobuf:"bytes,1,rep,name=location" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Locations) Reset()         { *m = Locations{} }
func (m *Locations) String() string { return proto.CompactTextString(m) }
func (*Locations) ProtoMessage()    {}
func (*Locations) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{20}
}
func (m *Locations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Locations.Unmarshal(m, b)
}
func (m *Locations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Locations.Marshal(b, m, deterministic)
}
func (dst *Locations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Locations.Merge(dst, src)
}
func (m *Locations) XXX_Size() int {
	return xxx_messageInfo_Locations.Size(m)
}
func (m *Locations) XXX_DiscardUnknown() {
	xxx_messageInfo_Locations.DiscardUnknown(m)
}

var xxx_messageInfo_Locations proto.InternalMessageInfo

func (m *Locations) GetLocation() []*Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type PartitionInfo struct {
	Uuid                 *string                       `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	Path                 *string                       `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	State                *PartitionInfo_PartitionState `protobuf:"varint,3,req,name=state,enum=storageserver.PartitionInfo_PartitionState" json:"state,omitempty"`
	ErrorMessage         *string                       `protobuf:"bytes,4,opt,name=errorMessage" json:"errorMessage,omitempty"`
	SizeBytes            *int64                        `protobuf:"varint,5,req,name=sizeBytes" json:"sizeBytes,omitempty"`
	AvailableBytes       *int64                        `protobuf:"varint,6,req,name=availableBytes" json:"availableBytes,omitempty"`
	BlockBinInfo         []*PartitionInfo_BlockBinInfo `protobuf:"bytes,7,rep,name=blockBinInfo" json:"blockBinInfo,omitempty"`
	SerialNumber         *string                       `protobuf:"bytes,8,opt,name=serialNumber" json:"serialNumber,omitempty"`
	Slot                 *string                       `protobuf:"bytes,9,opt,name=slot" json:"slot,omitempty"`
	Device               *string                       `protobuf:"bytes,10,opt,name=device" json:"device,omitempty"`
	IsSSD                *bool                         `protobuf:"varint,11,opt,name=isSSD" json:"isSSD,omitempty"`
	Locations            *Locations                    `protobuf:"bytes,12,opt,name=locations" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PartitionInfo) Reset()         { *m = PartitionInfo{} }
func (m *PartitionInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionInfo) ProtoMessage()    {}
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{21}
}
func (m *PartitionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionInfo.Unmarshal(m, b)
}
func (m *PartitionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionInfo.Marshal(b, m, deterministic)
}
func (dst *PartitionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionInfo.Merge(dst, src)
}
func (m *PartitionInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionInfo.Size(m)
}
func (m *PartitionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionInfo proto.InternalMessageInfo

func (m *PartitionInfo) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *PartitionInfo) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *PartitionInfo) GetState() PartitionInfo_PartitionState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return PartitionInfo_UNKNOWN
}

func (m *PartitionInfo) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

func (m *PartitionInfo) GetSizeBytes() int64 {
	if m != nil && m.SizeBytes != nil {
		return *m.SizeBytes
	}
	return 0
}

func (m *PartitionInfo) GetAvailableBytes() int64 {
	if m != nil && m.AvailableBytes != nil {
		return *m.AvailableBytes
	}
	return 0
}

func (m *PartitionInfo) GetBlockBinInfo() []*PartitionInfo_BlockBinInfo {
	if m != nil {
		return m.BlockBinInfo
	}
	return nil
}

func (m *PartitionInfo) GetSerialNumber() string {
	if m != nil && m.SerialNumber != nil {
		return *m.SerialNumber
	}
	return ""
}

func (m *PartitionInfo) GetSlot() string {
	if m != nil && m.Slot != nil {
		return *m.Slot
	}
	return ""
}

func (m *PartitionInfo) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *PartitionInfo) GetIsSSD() bool {
	if m != nil && m.IsSSD != nil {
		return *m.IsSSD
	}
	return false
}

func (m *PartitionInfo) GetLocations() *Locations {
	if m != nil {
		return m.Locations
	}
	return nil
}

type PartitionInfo_BlockBinInfo struct {
	Id                   *string                                   `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Size                 *int64                                    `protobuf:"varint,2,req,name=size" json:"size,omitempty"`
	State                *PartitionInfo_BlockBinInfo_BlockBinState `protobuf:"varint,3,req,name=state,enum=storageserver.PartitionInfo_BlockBinInfo_BlockBinState" json:"state,omitempty"`
	ErrorMessage         *string                                   `protobuf:"bytes,4,opt,name=errorMessage" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *PartitionInfo_BlockBinInfo) Reset()         { *m = PartitionInfo_BlockBinInfo{} }
func (m *PartitionInfo_BlockBinInfo) String() string { return proto.CompactTextString(m) }
func (*PartitionInfo_BlockBinInfo) ProtoMessage()    {}
func (*PartitionInfo_BlockBinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{21, 0}
}
func (m *PartitionInfo_BlockBinInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionInfo_BlockBinInfo.Unmarshal(m, b)
}
func (m *PartitionInfo_BlockBinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionInfo_BlockBinInfo.Marshal(b, m, deterministic)
}
func (dst *PartitionInfo_BlockBinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionInfo_BlockBinInfo.Merge(dst, src)
}
func (m *PartitionInfo_BlockBinInfo) XXX_Size() int {
	return xxx_messageInfo_PartitionInfo_BlockBinInfo.Size(m)
}
func (m *PartitionInfo_BlockBinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionInfo_BlockBinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionInfo_BlockBinInfo proto.InternalMessageInfo

func (m *PartitionInfo_BlockBinInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *PartitionInfo_BlockBinInfo) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *PartitionInfo_BlockBinInfo) GetState() PartitionInfo_BlockBinInfo_BlockBinState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return PartitionInfo_BlockBinInfo_ONLINE
}

func (m *PartitionInfo_BlockBinInfo) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{22}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	StorageServerId      *string  `protobuf:"bytes,1,req,name=storageServerId" json:"storageServerId,omitempty"`
	Status               *Status  `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	ChangeId             *int64   `protobuf:"varint,3,req,name=changeId" json:"changeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{23}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStorageServerId() string {
	if m != nil && m.StorageServerId != nil {
		return *m.StorageServerId
	}
	return ""
}

func (m *StatusResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StatusResponse) GetChangeId() int64 {
	if m != nil && m.ChangeId != nil {
		return *m.ChangeId
	}
	return 0
}

type Status struct {
	ServerStartTime      *string  `protobuf:"bytes,1,req,name=serverStartTime" json:"serverStartTime,omitempty"`
	RequestCount         *int64   `protobuf:"varint,2,req,name=requestCount" json:"requestCount,omitempty"`
	RequestErrorCount    *int64   `protobuf:"varint,3,req,name=requestErrorCount" json:"requestErrorCount,omitempty"`
	PartitionCount       *int64   `protobuf:"varint,4,req,name=partitionCount" json:"partitionCount,omitempty"`
	PartitionError       *int64   `protobuf:"varint,5,req,name=partitionError" json:"partitionError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{24}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetServerStartTime() string {
	if m != nil && m.ServerStartTime != nil {
		return *m.ServerStartTime
	}
	return ""
}

func (m *Status) GetRequestCount() int64 {
	if m != nil && m.RequestCount != nil {
		return *m.RequestCount
	}
	return 0
}

func (m *Status) GetRequestErrorCount() int64 {
	if m != nil && m.RequestErrorCount != nil {
		return *m.RequestErrorCount
	}
	return 0
}

func (m *Status) GetPartitionCount() int64 {
	if m != nil && m.PartitionCount != nil {
		return *m.PartitionCount
	}
	return 0
}

func (m *Status) GetPartitionError() int64 {
	if m != nil && m.PartitionError != nil {
		return *m.PartitionError
	}
	return 0
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{25}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type IOStats struct {
	AverageReadRequestTime    *uint64  `protobuf:"varint,1,req,name=averageReadRequestTime" json:"averageReadRequestTime,omitempty"`
	AverageWriteRequestTime   *uint64  `protobuf:"varint,2,req,name=averageWriteRequestTime" json:"averageWriteRequestTime,omitempty"`
	EstimatedReadRequestTime  *uint64  `protobuf:"varint,3,req,name=estimatedReadRequestTime" json:"estimatedReadRequestTime,omitempty"`
	EstimatedWriteRequestTime *uint64  `protobuf:"varint,4,req,name=estimatedWriteRequestTime" json:"estimatedWriteRequestTime,omitempty"`
	ReadOperations            *uint64  `protobuf:"varint,5,req,name=readOperations" json:"readOperations,omitempty"`
	WriteOperations           *uint64  `protobuf:"varint,6,req,name=writeOperations" json:"writeOperations,omitempty"`
	AverageReadTime           *uint64  `protobuf:"varint,7,req,name=averageReadTime" json:"averageReadTime,omitempty"`
	AverageWriteTime          *uint64  `protobuf:"varint,8,req,name=averageWriteTime" json:"averageWriteTime,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *IOStats) Reset()         { *m = IOStats{} }
func (m *IOStats) String() string { return proto.CompactTextString(m) }
func (*IOStats) ProtoMessage()    {}
func (*IOStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{26}
}
func (m *IOStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IOStats.Unmarshal(m, b)
}
func (m *IOStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IOStats.Marshal(b, m, deterministic)
}
func (dst *IOStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOStats.Merge(dst, src)
}
func (m *IOStats) XXX_Size() int {
	return xxx_messageInfo_IOStats.Size(m)
}
func (m *IOStats) XXX_DiscardUnknown() {
	xxx_messageInfo_IOStats.DiscardUnknown(m)
}

var xxx_messageInfo_IOStats proto.InternalMessageInfo

func (m *IOStats) GetAverageReadRequestTime() uint64 {
	if m != nil && m.AverageReadRequestTime != nil {
		return *m.AverageReadRequestTime
	}
	return 0
}

func (m *IOStats) GetAverageWriteRequestTime() uint64 {
	if m != nil && m.AverageWriteRequestTime != nil {
		return *m.AverageWriteRequestTime
	}
	return 0
}

func (m *IOStats) GetEstimatedReadRequestTime() uint64 {
	if m != nil && m.EstimatedReadRequestTime != nil {
		return *m.EstimatedReadRequestTime
	}
	return 0
}

func (m *IOStats) GetEstimatedWriteRequestTime() uint64 {
	if m != nil && m.EstimatedWriteRequestTime != nil {
		return *m.EstimatedWriteRequestTime
	}
	return 0
}

func (m *IOStats) GetReadOperations() uint64 {
	if m != nil && m.ReadOperations != nil {
		return *m.ReadOperations
	}
	return 0
}

func (m *IOStats) GetWriteOperations() uint64 {
	if m != nil && m.WriteOperations != nil {
		return *m.WriteOperations
	}
	return 0
}

func (m *IOStats) GetAverageReadTime() uint64 {
	if m != nil && m.AverageReadTime != nil {
		return *m.AverageReadTime
	}
	return 0
}

func (m *IOStats) GetAverageWriteTime() uint64 {
	if m != nil && m.AverageWriteTime != nil {
		return *m.AverageWriteTime
	}
	return 0
}

type PartitionStats struct {
	Uuid                 *string  `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	Stats                *IOStats `protobuf:"bytes,2,req,name=stats" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionStats) Reset()         { *m = PartitionStats{} }
func (m *PartitionStats) String() string { return proto.CompactTextString(m) }
func (*PartitionStats) ProtoMessage()    {}
func (*PartitionStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{27}
}
func (m *PartitionStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionStats.Unmarshal(m, b)
}
func (m *PartitionStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionStats.Marshal(b, m, deterministic)
}
func (dst *PartitionStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionStats.Merge(dst, src)
}
func (m *PartitionStats) XXX_Size() int {
	return xxx_messageInfo_PartitionStats.Size(m)
}
func (m *PartitionStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionStats.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionStats proto.InternalMessageInfo

func (m *PartitionStats) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *PartitionStats) GetStats() *IOStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type PingResponse struct {
	PartitionStats       []*PartitionStats `protobuf:"bytes,1,rep,name=partitionStats" json:"partitionStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{28}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (dst *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(dst, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetPartitionStats() []*PartitionStats {
	if m != nil {
		return m.PartitionStats
	}
	return nil
}

type Event struct {
	EventId              *int64          `protobuf:"varint,1,req,name=eventId" json:"eventId,omitempty"`
	EventMessage         *int64          `protobuf:"varint,2,req,name=eventMessage" json:"eventMessage,omitempty"`
	DateTime             *string         `protobuf:"bytes,3,req,name=dateTime" json:"dateTime,omitempty"`
	Severity             *Event_Severity `protobuf:"varint,4,req,name=severity,enum=storageserver.Event_Severity" json:"severity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{29}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() int64 {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return 0
}

func (m *Event) GetEventMessage() int64 {
	if m != nil && m.EventMessage != nil {
		return *m.EventMessage
	}
	return 0
}

func (m *Event) GetDateTime() string {
	if m != nil && m.DateTime != nil {
		return *m.DateTime
	}
	return ""
}

func (m *Event) GetSeverity() Event_Severity {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return Event_INFORMATIONAL
}

type EventRequest struct {
	StorageServerId      *string  `protobuf:"bytes,1,req,name=storageServerId" json:"storageServerId,omitempty"`
	Event                *Event   `protobuf:"bytes,2,req,name=event" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{30}
}
func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (dst *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(dst, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetStorageServerId() string {
	if m != nil && m.StorageServerId != nil {
		return *m.StorageServerId
	}
	return ""
}

func (m *EventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type ConnectionPoolRequest struct {
	PoolId               *string  `protobuf:"bytes,1,req,name=poolId" json:"poolId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionPoolRequest) Reset()         { *m = ConnectionPoolRequest{} }
func (m *ConnectionPoolRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolRequest) ProtoMessage()    {}
func (*ConnectionPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{31}
}
func (m *ConnectionPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPoolRequest.Unmarshal(m, b)
}
func (m *ConnectionPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPoolRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectionPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPoolRequest.Merge(dst, src)
}
func (m *ConnectionPoolRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionPoolRequest.Size(m)
}
func (m *ConnectionPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPoolRequest proto.InternalMessageInfo

func (m *ConnectionPoolRequest) GetPoolId() string {
	if m != nil && m.PoolId != nil {
		return *m.PoolId
	}
	return ""
}

type ConnectionPoolResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionPoolResponse) Reset()         { *m = ConnectionPoolResponse{} }
func (m *ConnectionPoolResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionPoolResponse) ProtoMessage()    {}
func (*ConnectionPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{32}
}
func (m *ConnectionPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPoolResponse.Unmarshal(m, b)
}
func (m *ConnectionPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPoolResponse.Marshal(b, m, deterministic)
}
func (dst *ConnectionPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPoolResponse.Merge(dst, src)
}
func (m *ConnectionPoolResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionPoolResponse.Size(m)
}
func (m *ConnectionPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPoolResponse proto.InternalMessageInfo

type Entry struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{33}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Entry) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type MgmtRequest struct {
	Cmd                  *string  `protobuf:"bytes,1,req,name=cmd" json:"cmd,omitempty"`
	Parameters           []*Entry `protobuf:"bytes,2,rep,name=parameters" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtRequest) Reset()         { *m = MgmtRequest{} }
func (m *MgmtRequest) String() string { return proto.CompactTextString(m) }
func (*MgmtRequest) ProtoMessage()    {}
func (*MgmtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{34}
}
func (m *MgmtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtRequest.Unmarshal(m, b)
}
func (m *MgmtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtRequest.Marshal(b, m, deterministic)
}
func (dst *MgmtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtRequest.Merge(dst, src)
}
func (m *MgmtRequest) XXX_Size() int {
	return xxx_messageInfo_MgmtRequest.Size(m)
}
func (m *MgmtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtRequest proto.InternalMessageInfo

func (m *MgmtRequest) GetCmd() string {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ""
}

func (m *MgmtRequest) GetParameters() []*Entry {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type MgmtResponse struct {
	Results              []*Entry `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtResponse) Reset()         { *m = MgmtResponse{} }
func (m *MgmtResponse) String() string { return proto.CompactTextString(m) }
func (*MgmtResponse) ProtoMessage()    {}
func (*MgmtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_52acb9e2a41c6286, []int{35}
}
func (m *MgmtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtResponse.Unmarshal(m, b)
}
func (m *MgmtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtResponse.Marshal(b, m, deterministic)
}
func (dst *MgmtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtResponse.Merge(dst, src)
}
func (m *MgmtResponse) XXX_Size() int {
	return xxx_messageInfo_MgmtResponse.Size(m)
}
func (m *MgmtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtResponse proto.InternalMessageInfo

func (m *MgmtResponse) GetResults() []*Entry {
	if m != nil {
		return m.Results
	}
	return nil
}

var E_WriteRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*WriteRequest)(nil),
	Field:         1000,
	Name:          "storageserver.writeRequest",
	Tag:           "bytes,1000,opt,name=writeRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_ReadRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*ReadRequest)(nil),
	Field:         1001,
	Name:          "storageserver.readRequest",
	Tag:           "bytes,1001,opt,name=readRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_VerifyRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*VerifyDataRequest)(nil),
	Field:         1002,
	Name:          "storageserver.verifyRequest",
	Tag:           "bytes,1002,opt,name=verifyRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_ConfigRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*ConfigurationRequest)(nil),
	Field:         1003,
	Name:          "storageserver.configRequest",
	Tag:           "bytes,1003,opt,name=configRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_StatusRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*StatusRequest)(nil),
	Field:         1004,
	Name:          "storageserver.statusRequest",
	Tag:           "bytes,1004,opt,name=statusRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_CopyFromRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*CopyFromRequest)(nil),
	Field:         1005,
	Name:          "storageserver.copyFromRequest",
	Tag:           "bytes,1005,opt,name=copyFromRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_SyncBlockBinRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*SyncBlockBinRequest)(nil),
	Field:         1006,
	Name:          "storageserver.syncBlockBinRequest",
	Tag:           "bytes,1006,opt,name=syncBlockBinRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_EventRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*EventRequest)(nil),
	Field:         1007,
	Name:          "storageserver.eventRequest",
	Tag:           "bytes,1007,opt,name=eventRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_ConnectionPoolRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*ConnectionPoolRequest)(nil),
	Field:         1008,
	Name:          "storageserver.connectionPoolRequest",
	Tag:           "bytes,1008,opt,name=connectionPoolRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_MgmtRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*MgmtRequest)(nil),
	Field:         1009,
	Name:          "storageserver.mgmtRequest",
	Tag:           "bytes,1009,opt,name=mgmtRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_PingRequest = &proto.ExtensionDesc{
	ExtendedType:  (*Request)(nil),
	ExtensionType: (*PingRequest)(nil),
	Field:         1010,
	Name:          "storageserver.pingRequest",
	Tag:           "bytes,1010,opt,name=pingRequest",
	Filename:      "protocolbuffer/storage.proto",
}

var E_WriteResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*WriteResponse)(nil),
	Field:         1000,
	Name:          "storageserver.writeResponse",
	Tag:           "bytes,1000,opt,name=writeResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_ReadResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*ReadResponse)(nil),
	Field:         1001,
	Name:          "storageserver.readResponse",
	Tag:           "bytes,1001,opt,name=readResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_VerifyResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*VerifyDataResponse)(nil),
	Field:         1002,
	Name:          "storageserver.verifyResponse",
	Tag:           "bytes,1002,opt,name=verifyResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_ConfigResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*ConfigurationResponse)(nil),
	Field:         1003,
	Name:          "storageserver.configResponse",
	Tag:           "bytes,1003,opt,name=configResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_StatusResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*StatusResponse)(nil),
	Field:         1004,
	Name:          "storageserver.statusResponse",
	Tag:           "bytes,1004,opt,name=statusResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_CopyFromResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*CopyFromResponse)(nil),
	Field:         1005,
	Name:          "storageserver.copyFromResponse",
	Tag:           "bytes,1005,opt,name=copyFromResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_SyncBlockBinResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*SyncBlockBinResponse)(nil),
	Field:         1006,
	Name:          "storageserver.syncBlockBinResponse",
	Tag:           "bytes,1006,opt,name=syncBlockBinResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_ConnectionPoolResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*ConnectionPoolResponse)(nil),
	Field:         1007,
	Name:          "storageserver.connectionPoolResponse",
	Tag:           "bytes,1007,opt,name=connectionPoolResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_MgmtResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*MgmtResponse)(nil),
	Field:         1008,
	Name:          "storageserver.mgmtResponse",
	Tag:           "bytes,1008,opt,name=mgmtResponse",
	Filename:      "protocolbuffer/storage.proto",
}

var E_PingResponse = &proto.ExtensionDesc{
	ExtendedType:  (*Response)(nil),
	ExtensionType: (*PingResponse)(nil),
	Field:         1009,
	Name:          "storageserver.pingResponse",
	Tag:           "bytes,1009,opt,name=pingResponse",
	Filename:      "protocolbuffer/storage.proto",
}

func init() {
	proto.RegisterType((*Request)(nil), "storageserver.Request")
	proto.RegisterType((*Response)(nil), "storageserver.Response")
	proto.RegisterType((*RequestMetadata)(nil), "storageserver.RequestMetadata")
	proto.RegisterType((*SyncBlockBinRequest)(nil), "storageserver.SyncBlockBinRequest")
	proto.RegisterType((*SyncBlockBinResponse)(nil), "storageserver.SyncBlockBinResponse")
	proto.RegisterType((*WriteRequest)(nil), "storageserver.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "storageserver.WriteResponse")
	proto.RegisterType((*ReadRequest)(nil), "storageserver.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "storageserver.ReadResponse")
	proto.RegisterType((*VerifyDataRequest)(nil), "storageserver.VerifyDataRequest")
	proto.RegisterType((*VerifyDataResponse)(nil), "storageserver.VerifyDataResponse")
	proto.RegisterType((*CopyFromRequest)(nil), "storageserver.CopyFromRequest")
	proto.RegisterType((*CopyFromResponse)(nil), "storageserver.CopyFromResponse")
	proto.RegisterType((*SetConfigurationRequest)(nil), "storageserver.SetConfigurationRequest")
	proto.RegisterType((*SetConfigurationResponse)(nil), "storageserver.SetConfigurationResponse")
	proto.RegisterType((*ConfigurationRequest)(nil), "storageserver.ConfigurationRequest")
	proto.RegisterType((*ConfigurationRequestForSSD)(nil), "storageserver.ConfigurationRequestForSSD")
	proto.RegisterType((*ConfigurationResponse)(nil), "storageserver.ConfigurationResponse")
	proto.RegisterType((*Configuration)(nil), "storageserver.Configuration")
	proto.RegisterType((*Location)(nil), "storageserver.Location")
	proto.RegisterType((*Locations)(nil), "storageserver.Locations")
	proto.RegisterType((*PartitionInfo)(nil), "storageserver.PartitionInfo")
	proto.RegisterType((*PartitionInfo_BlockBinInfo)(nil), "storageserver.PartitionInfo.BlockBinInfo")
	proto.RegisterType((*StatusRequest)(nil), "storageserver.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "storageserver.StatusResponse")
	proto.RegisterType((*Status)(nil), "storageserver.Status")
	proto.RegisterType((*PingRequest)(nil), "storageserver.PingRequest")
	proto.RegisterType((*IOStats)(nil), "storageserver.IOStats")
	proto.RegisterType((*PartitionStats)(nil), "storageserver.PartitionStats")
	proto.RegisterType((*PingResponse)(nil), "storageserver.PingResponse")
	proto.RegisterType((*Event)(nil), "storageserver.Event")
	proto.RegisterType((*EventRequest)(nil), "storageserver.EventRequest")
	proto.RegisterType((*ConnectionPoolRequest)(nil), "storageserver.ConnectionPoolRequest")
	proto.RegisterType((*ConnectionPoolResponse)(nil), "storageserver.ConnectionPoolResponse")
	proto.RegisterType((*Entry)(nil), "storageserver.Entry")
	proto.RegisterType((*MgmtRequest)(nil), "storageserver.MgmtRequest")
	proto.RegisterType((*MgmtResponse)(nil), "storageserver.MgmtResponse")
	proto.RegisterEnum("storageserver.Response_Status", Response_Status_name, Response_Status_value)
	proto.RegisterEnum("storageserver.PartitionInfo_PartitionState", PartitionInfo_PartitionState_name, PartitionInfo_PartitionState_value)
	proto.RegisterEnum("storageserver.PartitionInfo_BlockBinInfo_BlockBinState", PartitionInfo_BlockBinInfo_BlockBinState_name, PartitionInfo_BlockBinInfo_BlockBinState_value)
	proto.RegisterEnum("storageserver.Event_Severity", Event_Severity_name, Event_Severity_value)
	proto.RegisterExtension(E_WriteRequest)
	proto.RegisterExtension(E_ReadRequest)
	proto.RegisterExtension(E_VerifyRequest)
	proto.RegisterExtension(E_ConfigRequest)
	proto.RegisterExtension(E_StatusRequest)
	proto.RegisterExtension(E_CopyFromRequest)
	proto.RegisterExtension(E_SyncBlockBinRequest)
	proto.RegisterExtension(E_EventRequest)
	proto.RegisterExtension(E_ConnectionPoolRequest)
	proto.RegisterExtension(E_MgmtRequest)
	proto.RegisterExtension(E_PingRequest)
	proto.RegisterExtension(E_WriteResponse)
	proto.RegisterExtension(E_ReadResponse)
	proto.RegisterExtension(E_VerifyResponse)
	proto.RegisterExtension(E_ConfigResponse)
	proto.RegisterExtension(E_StatusResponse)
	proto.RegisterExtension(E_CopyFromResponse)
	proto.RegisterExtension(E_SyncBlockBinResponse)
	proto.RegisterExtension(E_ConnectionPoolResponse)
	proto.RegisterExtension(E_MgmtResponse)
	proto.RegisterExtension(E_PingResponse)
}

func init() {
	proto.RegisterFile("protocolbuffer/storage.proto", fileDescriptor_storage_52acb9e2a41c6286)
}

var fileDescriptor_storage_52acb9e2a41c6286 = []byte{
	// 1998 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdb, 0x8e, 0xe3, 0x48,
	0x19, 0xc6, 0x49, 0x9c, 0xc3, 0x9f, 0x93, 0xdb, 0xd3, 0x07, 0xcf, 0xd0, 0xbb, 0x9b, 0xf5, 0xd0,
	0x4b, 0x76, 0x57, 0xca, 0xa0, 0x5e, 0x2d, 0x48, 0x41, 0x02, 0x75, 0xa7, 0xd3, 0x90, 0xd9, 0x74,
	0x32, 0xc4, 0x3d, 0x33, 0x20, 0x90, 0x56, 0x6e, 0xa7, 0x92, 0x58, 0xed, 0xd8, 0xc1, 0x55, 0xce,
	0x10, 0xae, 0x46, 0x70, 0xc1, 0x0b, 0xf0, 0x12, 0xdc, 0xf0, 0x22, 0x20, 0x2e, 0x78, 0x02, 0x2e,
	0x77, 0x19, 0x58, 0x76, 0xe1, 0x05, 0x50, 0x95, 0xcb, 0x8e, 0x9d, 0xd8, 0xe9, 0x46, 0x62, 0xef,
	0x92, 0x3a, 0x7c, 0xf5, 0xfd, 0x87, 0xef, 0xaf, 0xbf, 0x0c, 0xc7, 0x0b, 0xd7, 0x21, 0x8e, 0xe1,
	0x58, 0x37, 0xde, 0x64, 0x82, 0xdc, 0x27, 0x98, 0x38, 0xae, 0x3e, 0x45, 0x2d, 0x36, 0x2c, 0x57,
	0xf9, 0x5f, 0x8c, 0xdc, 0x25, 0x72, 0xd5, 0xdf, 0x0a, 0x50, 0x18, 0xa1, 0x5f, 0x7a, 0x08, 0x13,
	0xb9, 0x0e, 0x85, 0x25, 0x72, 0xb1, 0xe9, 0xd8, 0x8a, 0xd0, 0xc8, 0x34, 0xb3, 0xf2, 0x11, 0xd4,
	0xe7, 0x08, 0x63, 0x7d, 0x8a, 0x3a, 0x33, 0x64, 0xdc, 0x6a, 0xde, 0x5c, 0xc9, 0x34, 0x32, 0xcd,
	0x0a, 0x5d, 0x69, 0x38, 0x36, 0x41, 0xbf, 0x22, 0x4a, 0xb6, 0x21, 0x34, 0x2b, 0xf2, 0x1e, 0x94,
	0x5c, 0x1f, 0xa5, 0x37, 0x56, 0x72, 0x0d, 0xa1, 0x59, 0x92, 0x6b, 0x90, 0x77, 0x5c, 0x73, 0x6a,
	0xda, 0x8a, 0xc8, 0xfe, 0xd7, 0xa1, 0x40, 0xcc, 0x39, 0x72, 0x3c, 0xa2, 0xe4, 0x1b, 0x42, 0x33,
	0xf7, 0x41, 0xa9, 0xf8, 0x59, 0x41, 0x7a, 0xfd, 0xfa, 0xf5, 0xeb, 0x8c, 0xfa, 0x27, 0x01, 0x8a,
	0x23, 0x84, 0x17, 0x8e, 0x8d, 0xd1, 0x36, 0x8d, 0x16, 0xe4, 0x31, 0xd1, 0x89, 0x87, 0xd9, 0xe9,
	0xb5, 0xd3, 0xb7, 0x5b, 0x31, 0x1b, 0x5a, 0xc1, 0xce, 0x96, 0xc6, 0x56, 0x25, 0xd1, 0xce, 0x32,
	0xda, 0xfb, 0x50, 0x41, 0xae, 0xeb, 0xb8, 0x57, 0xfe, 0x2c, 0x27, 0x1a, 0x31, 0x46, 0xdc, 0x36,
	0x86, 0x72, 0x2d, 0xa9, 0x0d, 0xc8, 0x73, 0xf0, 0x32, 0x14, 0xb4, 0xe7, 0x9d, 0x4e, 0x57, 0xd3,
	0x24, 0x41, 0x2e, 0x81, 0xd8, 0x1d, 0x8d, 0x86, 0x23, 0x29, 0x13, 0xb5, 0x66, 0x00, 0x75, 0xee,
	0xd2, 0x2b, 0x44, 0xf4, 0xb1, 0x4e, 0x74, 0x0a, 0x69, 0xcc, 0x3c, 0xfb, 0x56, 0x33, 0x7f, 0x8d,
	0x14, 0xa1, 0x21, 0x34, 0xab, 0xf2, 0x03, 0x28, 0xb3, 0xa1, 0xe1, 0x64, 0x82, 0x11, 0x51, 0x32,
	0xd4, 0x27, 0x74, 0x10, 0xcf, 0x1c, 0xcf, 0x1a, 0x77, 0x74, 0x63, 0x86, 0x98, 0x73, 0x8b, 0xea,
	0x02, 0x1e, 0x68, 0x2b, 0xdb, 0x38, 0xb7, 0x1c, 0xe3, 0xf6, 0xdc, 0xb4, 0x83, 0x70, 0x1d, 0x40,
	0x75, 0xa1, 0xbb, 0xc4, 0x24, 0xa6, 0x63, 0x3f, 0xf7, 0xcc, 0x31, 0xf3, 0x56, 0x49, 0x96, 0xa0,
	0x38, 0x31, 0x2d, 0x34, 0xd0, 0xe7, 0x88, 0xf9, 0xab, 0x24, 0x7f, 0x07, 0x8a, 0x73, 0x4e, 0x84,
	0x21, 0x96, 0x13, 0x3c, 0x18, 0xa3, 0xab, 0x3e, 0x81, 0xfd, 0xf8, 0x89, 0x3c, 0x34, 0x47, 0x50,
	0xf7, 0x77, 0x68, 0x44, 0x77, 0xc9, 0xb5, 0x39, 0x47, 0xfe, 0xa1, 0xea, 0xdf, 0x04, 0xa8, 0xbc,
	0x74, 0x4d, 0x82, 0xfe, 0x67, 0x72, 0x87, 0x50, 0xc3, 0x14, 0xcc, 0xb4, 0xa7, 0xdc, 0x13, 0x59,
	0x16, 0x74, 0x19, 0x80, 0x52, 0xe9, 0x23, 0x7b, 0x4a, 0x66, 0x4a, 0x8e, 0x8d, 0x3d, 0x84, 0x32,
	0x5e, 0xd9, 0xc6, 0xd0, 0x66, 0x47, 0xb1, 0x68, 0x15, 0xdb, 0x39, 0xe2, 0x7a, 0x88, 0x86, 0x96,
	0x2e, 0x0f, 0x03, 0x9e, 0x67, 0x91, 0x54, 0xa0, 0x84, 0x6f, 0xcd, 0x85, 0xbf, 0xbc, 0xc0, 0x96,
	0x8b, 0x13, 0xdd, 0xc2, 0x28, 0xe6, 0x93, 0xe2, 0xbd, 0x7c, 0xf2, 0x03, 0xa8, 0x72, 0x0b, 0xb9,
	0x33, 0x36, 0x8f, 0x14, 0xd8, 0x91, 0x09, 0x2e, 0xca, 0xb0, 0x14, 0xfa, 0xbd, 0x00, 0xe5, 0x11,
	0xd2, 0xc7, 0x5f, 0xab, 0x87, 0xa2, 0x66, 0x89, 0xf7, 0x32, 0x4b, 0x85, 0x8a, 0xcf, 0x8a, 0x5b,
	0x15, 0x47, 0x65, 0x02, 0x54, 0x67, 0xb0, 0xf7, 0x02, 0xb9, 0xe6, 0x64, 0x75, 0xa1, 0x13, 0xfd,
	0xeb, 0xe4, 0xaf, 0x7e, 0x00, 0x72, 0xf4, 0xa4, 0x54, 0x4f, 0x67, 0x9a, 0x15, 0xf5, 0xaf, 0x02,
	0xd4, 0x3b, 0xce, 0x62, 0x75, 0xe9, 0x3a, 0xf3, 0x80, 0x94, 0x02, 0x12, 0x76, 0x3c, 0xd7, 0x40,
	0x1a, 0xb3, 0x96, 0xb1, 0xf0, 0x79, 0x3d, 0x02, 0x19, 0x3b, 0x9e, 0x81, 0x9e, 0xc5, 0x38, 0xaf,
	0x19, 0xb2, 0x5d, 0x97, 0x01, 0xf3, 0x2c, 0x1b, 0x3f, 0x86, 0x7d, 0x8e, 0x16, 0xe7, 0x9f, 0x63,
	0xb3, 0x5b, 0x0e, 0x10, 0xb7, 0x1c, 0x90, 0x4f, 0x71, 0x40, 0x81, 0x8d, 0xc7, 0x1d, 0x50, 0x64,
	0x42, 0x6a, 0x82, 0xb4, 0xb6, 0x69, 0x57, 0xa2, 0xa9, 0xd7, 0x70, 0xa4, 0x21, 0xd2, 0x71, 0xec,
	0x89, 0x39, 0xf5, 0x5c, 0x9d, 0xb2, 0x08, 0xbc, 0x40, 0x73, 0xd0, 0x0f, 0xba, 0xef, 0x86, 0xde,
	0x98, 0xed, 0x29, 0xc9, 0x0d, 0x50, 0xc6, 0x68, 0xa2, 0x7b, 0x16, 0x09, 0xa4, 0x4d, 0x0b, 0xd2,
	0xf9, 0x8a, 0x20, 0xcc, 0xb2, 0x34, 0xab, 0x0e, 0x41, 0xd9, 0x46, 0xe5, 0x3c, 0x3e, 0x82, 0xaa,
	0x11, 0x9d, 0x60, 0x9e, 0x2d, 0x9f, 0x1e, 0x6f, 0x64, 0x58, 0x6c, 0xb3, 0xfa, 0x3b, 0x01, 0xf6,
	0x13, 0x49, 0x3e, 0x85, 0x23, 0x8c, 0xc7, 0x49, 0x53, 0x8a, 0xd0, 0xc8, 0x36, 0xcb, 0xa7, 0xef,
	0xef, 0xc2, 0xe5, 0x4b, 0x2f, 0x1d, 0x57, 0xd3, 0x2e, 0xe4, 0x2a, 0x88, 0x16, 0x5a, 0x22, 0x8b,
	0x19, 0x21, 0x52, 0x87, 0xcd, 0xcc, 0xe9, 0x0c, 0x61, 0xd2, 0x67, 0xa3, 0xb4, 0xe8, 0x89, 0xea,
	0x1f, 0x04, 0x78, 0xb4, 0x1b, 0x03, 0xe3, 0x71, 0x2f, 0xc8, 0xe3, 0x77, 0xe0, 0x28, 0xb8, 0x04,
	0xec, 0xa5, 0x6e, 0x99, 0x63, 0x9d, 0x20, 0x5e, 0x95, 0x69, 0xd2, 0x14, 0xe5, 0x8f, 0x60, 0xcf,
	0x76, 0x88, 0x39, 0x31, 0xd1, 0xb8, 0xef, 0x18, 0x0c, 0x10, 0xf3, 0xf2, 0xaa, 0x6c, 0x30, 0x0f,
	0xe7, 0xe5, 0xf7, 0x40, 0x24, 0xce, 0x2d, 0xb2, 0xd9, 0xd5, 0x53, 0x3e, 0x3d, 0x4a, 0x59, 0xa8,
	0xf6, 0xe1, 0xe0, 0xff, 0x18, 0x83, 0xbf, 0x08, 0x50, 0x8d, 0x8d, 0x24, 0x67, 0x08, 0x4f, 0x6a,
	0xbc, 0xc2, 0x96, 0x33, 0xed, 0xda, 0xfa, 0x8d, 0x85, 0xc6, 0xdc, 0x58, 0x7a, 0x2f, 0xb1, 0xe1,
	0x4b, 0x4b, 0x9f, 0x62, 0x2e, 0x8f, 0x5d, 0xd9, 0xe4, 0x97, 0xa3, 0x93, 0xf0, 0xe6, 0x16, 0x19,
	0xcd, 0x83, 0x0d, 0x9a, 0xfc, 0x4e, 0x7d, 0x02, 0xa5, 0x50, 0x49, 0x4a, 0x9e, 0x05, 0x7f, 0xd3,
	0xa0, 0x50, 0xb6, 0x3d, 0x7b, 0xe2, 0xa8, 0x3f, 0x81, 0x62, 0xe0, 0x2a, 0x4a, 0x2d, 0xdc, 0x1c,
	0x9a, 0x21, 0x03, 0xdc, 0x70, 0x4e, 0xbd, 0x40, 0xe5, 0xb4, 0x21, 0x89, 0xd6, 0x9f, 0x0a, 0xe4,
	0x30, 0xbd, 0x8e, 0xfd, 0xca, 0xf3, 0x5d, 0x28, 0xad, 0xc3, 0xf4, 0x3e, 0x14, 0x2d, 0xfe, 0x87,
	0x27, 0x63, 0x6a, 0xa4, 0xde, 0xe4, 0xa0, 0x1a, 0x23, 0x47, 0x71, 0xbd, 0x75, 0x3d, 0xac, 0x40,
	0x6e, 0xa1, 0x93, 0x19, 0xe7, 0xd0, 0x06, 0x91, 0x3a, 0xc4, 0x2f, 0x30, 0xb5, 0xd3, 0x0f, 0x77,
	0x59, 0xb9, 0xfe, 0x47, 0xdd, 0x84, 0x52, 0xba, 0x97, 0x3d, 0x28, 0xe1, 0xd0, 0xeb, 0x22, 0x33,
	0xec, 0x10, 0x6a, 0xfa, 0x52, 0x37, 0x2d, 0x1a, 0x40, 0x7f, 0x3c, 0xcf, 0xc6, 0x7f, 0x08, 0x95,
	0xd0, 0x29, 0xf6, 0xc4, 0x51, 0x0a, 0x89, 0x32, 0x8b, 0x73, 0x38, 0x8f, 0x6c, 0xa0, 0x0c, 0x30,
	0x72, 0x4d, 0xdd, 0x1a, 0x78, 0xf3, 0x1b, 0xe4, 0xb2, 0x8b, 0x93, 0x59, 0x88, 0x2d, 0x87, 0x28,
	0xa5, 0xa0, 0xed, 0x1b, 0xa3, 0xa5, 0x69, 0x20, 0x05, 0xd8, 0xff, 0x2a, 0x88, 0x26, 0xd6, 0xb4,
	0x0b, 0xa5, 0x4c, 0xaf, 0x5f, 0xf9, 0x43, 0x28, 0x59, 0xa1, 0x5a, 0x2a, 0xbb, 0xd5, 0xf2, 0xe8,
	0x8f, 0x02, 0x54, 0x62, 0x04, 0x00, 0x32, 0x51, 0xc7, 0xb2, 0xf0, 0x65, 0x98, 0x6d, 0x97, 0x71,
	0xc7, 0x7e, 0xef, 0xde, 0x46, 0x85, 0x7f, 0x76, 0x38, 0x59, 0x7d, 0x0f, 0xaa, 0xf1, 0x65, 0x00,
	0xf9, 0xe1, 0xa0, 0xdf, 0x1b, 0x74, 0x63, 0x4d, 0xa0, 0xfa, 0x29, 0xd4, 0x36, 0x82, 0x56, 0x86,
	0xc2, 0xf3, 0xc1, 0x27, 0x83, 0xe1, 0xcb, 0x81, 0xf4, 0x8d, 0xd8, 0xae, 0x32, 0x14, 0x86, 0x97,
	0x97, 0xec, 0x4f, 0x66, 0x0d, 0x91, 0xa5, 0xe3, 0xa3, 0xee, 0xd5, 0xf0, 0x45, 0xf7, 0x42, 0xca,
	0xc9, 0x75, 0x28, 0x5f, 0x9d, 0xf5, 0x06, 0xd7, 0xdd, 0xc1, 0xd9, 0xa0, 0xd3, 0x95, 0x44, 0xb5,
	0x0e, 0x55, 0x5f, 0x33, 0xbc, 0x76, 0xa9, 0x37, 0x50, 0x0b, 0x06, 0x22, 0x3d, 0x5a, 0xa2, 0xb4,
	0x4f, 0x62, 0x6d, 0x74, 0xaa, 0x18, 0x25, 0x28, 0x1a, 0x33, 0xdd, 0x9e, 0xa2, 0xde, 0xd8, 0x17,
	0x8a, 0xfa, 0x1b, 0x21, 0xec, 0x7e, 0xd3, 0x1a, 0x40, 0xea, 0x37, 0x5e, 0x2e, 0x3b, 0x8e, 0x67,
	0x13, 0x1e, 0x95, 0x87, 0xb0, 0xc7, 0x47, 0xbb, 0xd4, 0xa9, 0xfe, 0x54, 0x36, 0x48, 0xd2, 0x50,
	0xb6, 0xfe, 0x78, 0x6e, 0x6b, 0x9c, 0x6d, 0xf2, 0x93, 0x5a, 0xad, 0x42, 0xf9, 0x99, 0x69, 0x4f,
	0x03, 0xbb, 0xff, 0x23, 0x40, 0xa1, 0x37, 0xa4, 0xac, 0xb0, 0xfc, 0x36, 0x1c, 0xea, 0x4b, 0x44,
	0x2d, 0x89, 0xf4, 0x57, 0x21, 0xb7, 0x1c, 0x2d, 0xe5, 0x7c, 0x3e, 0xda, 0xa2, 0xf2, 0xd6, 0x8c,
	0x2e, 0x68, 0x80, 0x82, 0x30, 0x31, 0xe7, 0xb4, 0xc4, 0x6f, 0x42, 0x64, 0xd9, 0x8a, 0x77, 0xe1,
	0x61, 0xb8, 0x62, 0x0b, 0x24, 0xc7, 0x96, 0x1c, 0x42, 0xcd, 0x45, 0xfa, 0x78, 0xb8, 0x40, 0x2e,
	0x4f, 0x6f, 0x91, 0x8d, 0x1f, 0x41, 0xfd, 0x15, 0xdd, 0x11, 0x99, 0xc8, 0x07, 0x13, 0x11, 0xda,
	0x0c, 0xa9, 0xc0, 0x26, 0x14, 0x90, 0xa2, 0x7c, 0xd9, 0x0c, 0xed, 0x0e, 0x72, 0x6a, 0x77, 0x23,
	0xbf, 0xf0, 0x46, 0xb1, 0x39, 0xf1, 0x55, 0x10, 0x44, 0xf8, 0x70, 0x23, 0xc2, 0xdc, 0x61, 0x6a,
	0x17, 0x2a, 0xbe, 0x2f, 0x79, 0xca, 0x7c, 0x1c, 0xf1, 0x39, 0x5b, 0xc1, 0x8b, 0xde, 0x5b, 0x69,
	0x2a, 0xf2, 0x61, 0xfe, 0x2c, 0x80, 0xd8, 0x5d, 0x22, 0x9b, 0xbd, 0x1c, 0x11, 0xfd, 0xc1, 0x73,
	0x2d, 0xcb, 0x64, 0x44, 0x07, 0x02, 0x19, 0xf9, 0xe9, 0x20, 0x41, 0x91, 0x5e, 0xa3, 0xa1, 0x5f,
	0x4b, 0xf2, 0x13, 0x28, 0x62, 0xb4, 0x44, 0xae, 0x49, 0x56, 0xcc, 0x8d, 0xb5, 0xad, 0x33, 0xd9,
	0x01, 0x2d, 0x8d, 0x2f, 0x52, 0x7f, 0x06, 0xc5, 0xe0, 0xb7, 0xbc, 0x07, 0xd5, 0xde, 0xe0, 0x72,
	0x38, 0xba, 0x3a, 0xbb, 0xee, 0x0d, 0x07, 0x67, 0x7d, 0x5f, 0x8b, 0x9d, 0x7e, 0xf7, 0x6c, 0x24,
	0x65, 0xa8, 0x90, 0x5e, 0x9e, 0x8d, 0x06, 0xbd, 0xc1, 0x8f, 0xa4, 0x2c, 0x1d, 0xbf, 0xea, 0x0d,
	0x86, 0x23, 0x29, 0xc7, 0x7e, 0x9e, 0x3d, 0x1d, 0x8e, 0x24, 0x51, 0xae, 0x40, 0xb1, 0x33, 0xea,
	0x5d, 0xf7, 0x3a, 0x67, 0x7d, 0x29, 0xaf, 0xf6, 0xa1, 0xc2, 0x0e, 0xdb, 0xd9, 0x45, 0x51, 0xd2,
	0x8f, 0x41, 0x64, 0xc6, 0x71, 0x2f, 0xef, 0x27, 0x31, 0x56, 0xbf, 0xcd, 0x6e, 0x70, 0x1b, 0x19,
	0xd4, 0x5f, 0xcf, 0x1c, 0xc7, 0x0a, 0x60, 0x6b, 0x90, 0x5f, 0x38, 0x8e, 0x15, 0xa0, 0xa9, 0x0a,
	0x1c, 0x6e, 0x2e, 0xf4, 0xc3, 0xa2, 0x3e, 0x06, 0xb1, 0x6b, 0x13, 0x77, 0x25, 0x97, 0x21, 0x7b,
	0x8b, 0x56, 0xfc, 0xf4, 0x2a, 0x88, 0x4b, 0xdd, 0xf2, 0x78, 0x77, 0xad, 0x5e, 0x40, 0xf9, 0x6a,
	0x3a, 0x0f, 0x49, 0x97, 0x21, 0x6b, 0xcc, 0x03, 0xa2, 0x4d, 0x80, 0x85, 0xee, 0xea, 0x73, 0x44,
	0x90, 0x4b, 0x73, 0x22, 0x9b, 0xc4, 0x96, 0x9e, 0xa0, 0x7e, 0x0c, 0x15, 0x1f, 0x85, 0x67, 0xc4,
	0x09, 0x14, 0x5c, 0x84, 0x3d, 0x2b, 0x4c, 0x85, 0xc4, 0x6d, 0xed, 0xa7, 0x50, 0x79, 0x15, 0x7d,
	0xf5, 0x1d, 0x26, 0x3f, 0x36, 0x94, 0xcf, 0x0a, 0xac, 0xd2, 0x7f, 0x73, 0x63, 0x3a, 0xaa, 0xa4,
	0xf6, 0x8f, 0xa1, 0xec, 0x46, 0x9e, 0x47, 0x69, 0x50, 0x9f, 0xfb, 0x50, 0x8f, 0xb6, 0xa6, 0xc3,
	0xad, 0xed, 0x67, 0x50, 0x5d, 0xb2, 0x47, 0xc4, 0x5d, 0x58, 0x7f, 0xf7, 0xb1, 0x1a, 0x1b, 0xd3,
	0x5b, 0x6f, 0x9d, 0xb6, 0x16, 0x74, 0x5d, 0x77, 0x21, 0xbe, 0xf1, 0x11, 0x1f, 0xdf, 0xa3, 0x75,
	0x6d, 0xf7, 0xa1, 0x8a, 0xa3, 0xb5, 0x3c, 0x15, 0xf4, 0x1f, 0x3e, 0xe8, 0x71, 0x62, 0xbd, 0x5e,
	0x1b, 0x5d, 0x37, 0x36, 0x1e, 0x43, 0x69, 0x78, 0xff, 0x2c, 0x24, 0xbe, 0x0c, 0x37, 0xde, 0x52,
	0xed, 0x9f, 0xc2, 0x03, 0x9c, 0xf0, 0xd9, 0x21, 0x0d, 0xf5, 0x0b, 0x1f, 0x55, 0xdd, 0x64, 0xb9,
	0x0d, 0x41, 0xd3, 0x06, 0x45, 0x95, 0x96, 0x06, 0xf9, 0xaf, 0xe4, 0xb4, 0x89, 0xaa, 0xb4, 0xfd,
	0x0b, 0x38, 0x30, 0x12, 0x75, 0x96, 0x06, 0xfa, 0xa5, 0x0f, 0xfa, 0xad, 0xed, 0x10, 0x6d, 0x83,
	0xd0, 0xa4, 0x9c, 0x47, 0xd4, 0x95, 0x86, 0xf9, 0x55, 0x72, 0x52, 0x46, 0x84, 0x49, 0x91, 0x16,
	0xeb, 0xfb, 0x2b, 0x15, 0xe9, 0xdf, 0xc9, 0x48, 0x91, 0xab, 0xaf, 0x7d, 0x05, 0xd5, 0x57, 0xb1,
	0x0f, 0x11, 0x47, 0x29, 0xdf, 0xc3, 0x02, 0xd9, 0x1d, 0x27, 0xcb, 0xce, 0x5f, 0xd4, 0xfe, 0x84,
	0xde, 0xdc, 0x91, 0x0f, 0x00, 0xa9, 0x68, 0x9f, 0x27, 0x47, 0x23, 0xfa, 0xf5, 0xa0, 0xad, 0x41,
	0x2d, 0x90, 0xde, 0x5d, 0x70, 0x5c, 0x7c, 0xef, 0xee, 0x10, 0x1f, 0x07, 0x7d, 0x01, 0xb5, 0x40,
	0x7d, 0x77, 0x81, 0xbe, 0x49, 0x0d, 0xee, 0xf6, 0x5b, 0xaa, 0x3d, 0x64, 0xef, 0xf2, 0x58, 0xef,
	0x94, 0x86, 0xcb, 0x25, 0xf8, 0x56, 0x8a, 0x04, 0x43, 0xeb, 0x25, 0x63, 0xf3, 0xf1, 0x9e, 0x0a,
	0xc9, 0x55, 0xf8, 0x4e, 0xaa, 0x0a, 0x39, 0xe8, 0xcf, 0x61, 0x1f, 0x27, 0x7e, 0x8b, 0x4b, 0x03,
	0xfe, 0x22, 0xb9, 0x06, 0x25, 0x7d, 0xd0, 0x6b, 0x7f, 0x0a, 0x87, 0x46, 0xe2, 0xe5, 0x93, 0x0e,
	0xcf, 0x45, 0x79, 0x72, 0x87, 0x7e, 0xd6, 0xd9, 0x35, 0x8f, 0x5e, 0x2c, 0xa9, 0xb0, 0x5f, 0x26,
	0x67, 0x57, 0xf4, 0x56, 0xa2, 0x60, 0x8b, 0x68, 0xdf, 0x92, 0x0a, 0xf6, 0x55, 0x32, 0x58, 0xb4,
	0xe9, 0x39, 0xff, 0x3e, 0xa8, 0x86, 0x33, 0x6f, 0xa1, 0xb9, 0x11, 0xac, 0x72, 0x70, 0x6b, 0xac,
	0x13, 0xbd, 0x15, 0x7c, 0x3f, 0x6f, 0x61, 0x7c, 0x7e, 0xa0, 0x45, 0x5b, 0x00, 0xde, 0xce, 0xe0,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xce, 0xab, 0xde, 0xf0, 0x64, 0x17, 0x00, 0x00,
}
